/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador_persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan.torres
 */
public class FORMRECOMP extends javax.swing.JFrame {

    /**
     * Creates new form FORMRECOMP
     */
    public FORMRECOMP() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_recibo();
    }
public void cerrar_ventan_recibo() {
        setDefaultCloseOperation(FORMRECOMP.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanarecibo();
            }
        });
    }
   public void cerrar_ventanarecibo(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_cobrador = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        txt_bnombre_cobrador = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_bcobrador = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btn_agreg_cob = new javax.swing.JButton();
        ventana_moneda = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_bmoneda = new javax.swing.JTable();
        btn_agreg_moneda = new javax.swing.JButton();
        ventana_transaccion = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        txt_busq_transaccion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaccion = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btn_agreg_trans = new javax.swing.JButton();
        ventana_saldo_proveedor = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_saldo_prov = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btn_agreg_sal = new javax.swing.JButton();
        ventana_proveedor = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_busq_prov = new javax.swing.JTable();
        txt_bcod_prov = new javax.swing.JTextField();
        btn_agreg_busq = new javax.swing.JButton();
        txt_bnomb_prov = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_nuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cod_sucursal = new javax.swing.JTextField();
        txt_cod_tipo_comp = new javax.swing.JTextField();
        txt_nro_comp = new javax.swing.JTextField();
        txt_fecha_comp = new com.toedter.calendar.JDateChooser();
        txt_cod_prov = new javax.swing.JTextField();
        txt_desc_prov = new javax.swing.JTextField();
        txt_cod_moneda = new javax.swing.JTextField();
        txt_desc_moneda = new javax.swing.JTextField();
        txt_desc_sucursal = new javax.swing.JTextField();
        lbl_serie_nro = new javax.swing.JLabel();
        campo_obligatorio = new javax.swing.JLabel();
        lbl_fec_comp = new javax.swing.JLabel();
        lbl_cod_cliente = new javax.swing.JLabel();
        lbl_cod_moneda = new javax.swing.JLabel();
        txt_ser_comp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_sub_tipo_transaccion = new javax.swing.JTextField();
        txt_desc_tipo_transac = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_comprobante = new javax.swing.JTable();
        btn_limpiar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_total_comprobante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cod_usuario = new javax.swing.JTextField();
        txt_desc_usuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        ventana_cobrador.setTitle("COBRADORES");
        ventana_cobrador.setResizable(false);
        ventana_cobrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(txt_bnombre_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        tbl_bcobrador = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcobrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_bcobrador);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 260));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("Codigo Cobrador");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 35, -1, -1));

        btn_agreg_cob.setText("Agregar");
        btn_agreg_cob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_cobActionPerformed(evt);
            }
        });
        jPanel5.add(btn_agreg_cob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        ventana_cobrador.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        ventana_moneda.setTitle("MONEDAS");
        ventana_moneda.setResizable(false);
        ventana_moneda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bmoneda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bmoneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbl_bmoneda);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 90));

        btn_agreg_moneda.setText("Agregar");
        jPanel6.add(btn_agreg_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        ventana_moneda.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));

        ventana_transaccion.setTitle("VENTANA TRANSACCION");
        ventana_transaccion.setResizable(false);
        ventana_transaccion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(txt_busq_transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        tbl_transaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_transaccion);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, 200));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("Codigo");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 35, -1, -1));

        btn_agreg_trans.setText("Agregar");
        jPanel8.add(btn_agreg_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        ventana_transaccion.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        ventana_saldo_proveedor.setTitle("SALDOS CLIENTES");
        ventana_saldo_proveedor.setResizable(false);
        ventana_saldo_proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_saldo_prov = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_saldo_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_saldo_prov);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 680, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("PARA SELECCIONAR MAS DE  UNA FILA PULSE LA TECLA SHIFT");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, -1));

        btn_agreg_sal.setText("Agregar");
        btn_agreg_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_salActionPerformed(evt);
            }
        });
        jPanel9.add(btn_agreg_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 265, -1, -1));

        ventana_saldo_proveedor.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        ventana_proveedor.setTitle("BUSQUEDA PROVEEDOR");
        ventana_proveedor.setResizable(false);
        ventana_proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_busq_prov = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_busq_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_busq_prov);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 190));
        jPanel7.add(txt_bcod_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        btn_agreg_busq.setText("Agregar");
        jPanel7.add(btn_agreg_busq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        jPanel7.add(txt_bnomb_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 150, -1));

        ventana_proveedor.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECIBOS DE COMPRAS(FORMRECOMP)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);

        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyPressed(evt);
            }
        });
        jToolBar1.add(btn_nuevo);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GRABAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btnactualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setToolTipText("Modificar");
        jToolBar1.add(btnactualizar);

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncancelar);

        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btn_busqueda.setToolTipText("Buscar");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_busqueda);

        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.png"))); // NOI18N
        btn_ejecutar.setToolTipText("Buscar");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ejecutar);

        btn_imprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btn_imprimir.setToolTipText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_imprimir);

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        btn_ant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btn_ant.setToolTipText("Anterior reg");
        btn_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ant);

        btn_sig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        btn_sig.setToolTipText("Sigiente reg");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_sig);

        jPanel4.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 54));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DATOS PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Sucursal:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Tipo Comp:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Proveedor:(F9)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Moneda:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));
        jPanel1.add(txt_cod_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 20, 50, -1));
        jPanel1.add(txt_cod_tipo_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, 50, -1));

        txt_nro_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_compActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nro_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 50, 50, -1));
        jPanel1.add(txt_fecha_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 80, 130, -1));
        jPanel1.add(txt_cod_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 50, -1));
        jPanel1.add(txt_desc_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 250, -1));

        txt_cod_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_monedaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cod_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 145, 50, -1));

        txt_desc_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_monedaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_desc_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 145, 250, -1));
        jPanel1.add(txt_desc_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 250, -1));

        lbl_serie_nro.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_serie_nro.setForeground(new java.awt.Color(204, 204, 0));
        lbl_serie_nro.setText("*");
        jPanel1.add(lbl_serie_nro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 10, -1));

        campo_obligatorio.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        campo_obligatorio.setForeground(new java.awt.Color(204, 204, 0));
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS *");
        jPanel1.add(campo_obligatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 145, -1, -1));

        lbl_fec_comp.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_fec_comp.setForeground(new java.awt.Color(204, 204, 0));
        lbl_fec_comp.setText("*");
        jPanel1.add(lbl_fec_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        lbl_cod_cliente.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod_cliente.setForeground(new java.awt.Color(204, 204, 0));
        lbl_cod_cliente.setText("*");
        jPanel1.add(lbl_cod_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        lbl_cod_moneda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod_moneda.setForeground(new java.awt.Color(204, 204, 0));
        lbl_cod_moneda.setText("*");
        jPanel1.add(lbl_cod_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 145, -1, -1));

        txt_ser_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ser_compKeyTyped(evt);
            }
        });
        jPanel1.add(txt_ser_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 50, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, 180));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "TIPO TRANSACCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Transaccion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(txt_sub_tipo_transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 20, 50, -1));
        jPanel2.add(txt_desc_tipo_transac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DETALLE RECIBO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_comprobante = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_comprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_comprobante);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 710, 120));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17_2.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, 25));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Limpar Detalle");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 180));

        txt_total_comprobante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_comprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_comprobanteActionPerformed(evt);
            }
        });
        jPanel2.add(txt_total_comprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 240, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Total Recibo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 760, 280));
        jPanel4.add(txt_cod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 25, 70, 25));
        jPanel4.add(txt_desc_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 25, 220, 25));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("USUARIO");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 6, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyPressed

    }//GEN-LAST:event_btn_nuevoKeyPressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

    }//GEN-LAST:event_btncancelarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed

        //imprimir_comprobante();
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antActionPerformed

    }//GEN-LAST:event_btn_antActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed

    }//GEN-LAST:event_btn_sigActionPerformed

    private void txt_nro_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_compActionPerformed

    private void txt_cod_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_monedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_monedaActionPerformed

    private void txt_desc_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_monedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_monedaActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_total_comprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_comprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_comprobanteActionPerformed

    private void btn_agreg_cobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_cobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_cobActionPerformed

    private void btn_agreg_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_salActionPerformed

    private void txt_ser_compKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ser_compKeyTyped
       int num=7;
        if(txt_ser_comp.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_txt_ser_compKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMRECOMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMRECOMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMRECOMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMRECOMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMRECOMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agreg_busq;
    public javax.swing.JButton btn_agreg_cob;
    public javax.swing.JButton btn_agreg_moneda;
    public javax.swing.JButton btn_agreg_sal;
    public javax.swing.JButton btn_agreg_trans;
    public javax.swing.JButton btn_ant;
    public javax.swing.JButton btn_busqueda;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JButton btn_imprimir;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_sig;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JLabel campo_obligatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JLabel lbl_cod_cliente;
    public javax.swing.JLabel lbl_cod_moneda;
    public javax.swing.JLabel lbl_fec_comp;
    public javax.swing.JLabel lbl_serie_nro;
    public javax.swing.JTable tbl_bcobrador;
    public javax.swing.JTable tbl_bmoneda;
    public javax.swing.JTable tbl_busq_prov;
    public javax.swing.JTable tbl_comprobante;
    public javax.swing.JTable tbl_saldo_prov;
    public javax.swing.JTable tbl_transaccion;
    public javax.swing.JTextField txt_bcod_prov;
    public javax.swing.JTextField txt_bnomb_prov;
    public javax.swing.JTextField txt_bnombre_cobrador;
    public javax.swing.JTextField txt_busq_transaccion;
    public javax.swing.JTextField txt_cod_moneda;
    public javax.swing.JTextField txt_cod_prov;
    public javax.swing.JTextField txt_cod_sucursal;
    public javax.swing.JTextField txt_cod_tipo_comp;
    public javax.swing.JTextField txt_cod_usuario;
    public javax.swing.JTextField txt_desc_moneda;
    public javax.swing.JTextField txt_desc_prov;
    public javax.swing.JTextField txt_desc_sucursal;
    public javax.swing.JTextField txt_desc_tipo_transac;
    public javax.swing.JTextField txt_desc_usuario;
    public com.toedter.calendar.JDateChooser txt_fecha_comp;
    public javax.swing.JTextField txt_nro_comp;
    public javax.swing.JTextField txt_ser_comp;
    public javax.swing.JTextField txt_sub_tipo_transaccion;
    public javax.swing.JTextField txt_total_comprobante;
    private javax.swing.JDialog ventana_cobrador;
    private javax.swing.JDialog ventana_moneda;
    private javax.swing.JDialog ventana_proveedor;
    private javax.swing.JDialog ventana_saldo_proveedor;
    private javax.swing.JDialog ventana_transaccion;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_fecha();
        ocultar_labeles();
    }

    private void bloquea_campos() {
        txt_cod_prov.setEditable(false);
        txt_cod_moneda.setEditable(false);
        txt_cod_sucursal.setEditable(false);
        txt_cod_usuario.setEditable(false);
        txt_desc_usuario.setEditable(false);
        txt_cod_tipo_comp.setEditable(false);
        txt_desc_prov.setEditable(false);
        txt_desc_moneda.setEditable(false);
        txt_desc_sucursal.setEditable(false);
        txt_desc_tipo_transac.setEditable(false);
        txt_fecha_comp.setEnabled(false);
        txt_nro_comp.setEditable(false);
        txt_ser_comp.setEditable(false);
        txt_sub_tipo_transaccion.setEditable(false);
        txt_total_comprobante.setEditable(false);
    }
    public void habilita_campos() {
        txt_cod_prov.setEditable(true);
        txt_cod_moneda.setEditable(true);
        txt_cod_sucursal.setEditable(true);
        /*txt_cod_tipo_comp.setEditable(true);*/
        txt_desc_prov.setEditable(true);
        txt_desc_moneda.setEditable(true);
        txt_desc_sucursal.setEditable(true);
        txt_desc_tipo_transac.setEditable(true);
        txt_fecha_comp.setEnabled(true);
        txt_nro_comp.setEditable(true);
        txt_ser_comp.setEditable(true);
        txt_sub_tipo_transaccion.setEditable(true);
        txt_ser_comp.requestFocus();
    }
    private void bloquea_botones() {
        btn_sig.setVisible(false);
        btn_ant.setVisible(false);
        //btn_imprimir.setEnabled(false);
        btnactualizar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnguardar.setEnabled(false);
        btn_ejecutar.setEnabled(false);
        btn_busqueda.setEnabled(true);
        btn_nuevo.setEnabled(true);
        btn_nuevo.requestFocus();
    }

    private void carga_fecha() {
        try {
        Date hoy = new Date();
        Date fecha=null;
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
        String fechaact = formatofecha.format(hoy);
        fecha=formatofecha.parse(fechaact);
        txt_fecha_comp.setDate(fecha);
        } catch (ParseException ex) {
             Logger.getLogger(controlador_persona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ocultar_labeles() {
        lbl_serie_nro.setVisible(false);
        lbl_cod_cliente.setVisible(false);
        lbl_cod_moneda.setVisible(false);
        lbl_fec_comp.setVisible(false);
        campo_obligatorio.setVisible(false);
    }
    public void ventana_proveedor(){
      FORMRECOMP bus = new FORMRECOMP();
        ventana_proveedor.setVisible(true);
        ventana_proveedor.setSize(400,330);
        ventana_proveedor.setLocationRelativeTo(bus);
        txt_bcod_prov.setText("");
        txt_bnomb_prov.setText("%");
    }
    public void cerrar_ventana_proveedor(){
        ventana_proveedor.dispose();
    }
    public void ventana_moneda(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_moneda.setVisible(true);
        ventana_moneda.setSize(400,180);
        ventana_moneda.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_moneda(){
        ventana_moneda.dispose();
    }
    public void ventana_transaccion(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_transaccion.setVisible(true);
        ventana_transaccion.setSize(400,330);
        ventana_transaccion.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_transaccion(){
        ventana_transaccion.dispose();
    }
    public void ventana_saldo_proveedor(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_saldo_proveedor.setVisible(true);
        ventana_saldo_proveedor.setSize(710,320);
        ventana_saldo_proveedor.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_saldo_proveedor(){
        ventana_saldo_proveedor.dispose();
    }
    public void mostrar_labeles() {
        lbl_serie_nro.setVisible(true);
        lbl_cod_cliente.setVisible(true);
        lbl_cod_moneda.setVisible(true);
        lbl_fec_comp.setVisible(true);
        campo_obligatorio.setVisible(true);
    }
    public void limpia_campos() {
        txt_cod_prov.setText("");
        txt_cod_moneda.setText("");
        txt_desc_prov.setText("");
        txt_desc_moneda.setText("");
        txt_desc_tipo_transac.setText("");
        txt_nro_comp.setText("");
        txt_ser_comp.setText("");
        txt_sub_tipo_transaccion.setText("");
        txt_total_comprobante.setText("");
    }
}
