
package vista;

import controlador.controlador_persona;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JONY
 */
public class FORMRECIBO extends javax.swing.JFrame {

   
    public FORMRECIBO() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_recibo();
    }
public void cerrar_ventan_recibo() {
        setDefaultCloseOperation(FORMARTICU.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanarecibo();
            }
        });
    }
   public void cerrar_ventanarecibo(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_cobrador = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_bcobrador = new javax.swing.JTable();
        btn_agreg_cob = new javax.swing.JButton();
        ventana_moneda = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_bmoneda = new javax.swing.JTable();
        btn_agreg_moneda = new javax.swing.JButton();
        ventana_busqueda = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_bnomb_cliente = new javax.swing.JTextField();
        txt_bnro_documento = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_busqueda = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_agreg_busq = new javax.swing.JButton();
        ventana_transaccion = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaccion = new javax.swing.JTable();
        btn_agreg_trans = new javax.swing.JButton();
        ventana_saldo_cliente = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_saldo_cliente = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btn_agreg_sal = new javax.swing.JButton();
        ventana_talonario = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_busq_talonario = new javax.swing.JTable();
        btn_agreg_tal = new javax.swing.JButton();
        ventana_error = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_error = new javax.swing.JTextArea();
        btn_volver_err = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cod_sucursal = new javax.swing.JTextField();
        txt_cod_tipo_comp = new javax.swing.JTextField();
        txt_nro_comp = new javax.swing.JTextField();
        txt_fecha_comp = new com.toedter.calendar.JDateChooser();
        txt_cod_cliente = new javax.swing.JTextField();
        txt_desc_cliente = new javax.swing.JTextField();
        txt_cod_cobrador = new javax.swing.JTextField();
        txt_desc_cobrador = new javax.swing.JTextField();
        txt_cod_moneda = new javax.swing.JTextField();
        txt_desc_moneda = new javax.swing.JTextField();
        txt_desc_sucursal = new javax.swing.JTextField();
        lbl_serie_nro = new javax.swing.JLabel();
        campo_obligatorio = new javax.swing.JLabel();
        lbl_fec_comp = new javax.swing.JLabel();
        lbl_cod_cliente = new javax.swing.JLabel();
        lbl_cod_moneda = new javax.swing.JLabel();
        txt_ser_comp = new javax.swing.JTextField();
        btn_suc = new javax.swing.JButton();
        btn_mon = new javax.swing.JButton();
        btn_tip_comp = new javax.swing.JButton();
        btn_cli = new javax.swing.JButton();
        btn_cob = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_cod_usuario = new javax.swing.JTextField();
        txt_desc_usuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_sub_tipo_transaccion = new javax.swing.JTextField();
        txt_desc_tipo_transac = new javax.swing.JTextField();
        txt_total_comprobante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_trans = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_comprobante = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_error = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        ventana_cobrador.setTitle("COBRADORES");
        ventana_cobrador.setResizable(false);
        ventana_cobrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bcobrador = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcobrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_bcobrador);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 310));

        btn_agreg_cob.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_cob.setText("Agregar");
        btn_agreg_cob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_cobActionPerformed(evt);
            }
        });
        jPanel5.add(btn_agreg_cob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jPanel12.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 360));

        ventana_cobrador.getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        ventana_moneda.setTitle("MONEDAS");
        ventana_moneda.setResizable(false);
        ventana_moneda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bmoneda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bmoneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbl_bmoneda);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 90));

        btn_agreg_moneda.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_moneda.setText("Agregar");
        jPanel6.add(btn_agreg_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jPanel13.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 150));

        ventana_moneda.getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 180));

        ventana_busqueda.setTitle("VENTANA BUSQUEDA");
        ventana_busqueda.setResizable(false);
        ventana_busqueda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(txt_bnomb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, -1));

        txt_bnro_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bnro_documentoActionPerformed(evt);
            }
        });
        txt_bnro_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bnro_documentoKeyTyped(evt);
            }
        });
        jPanel7.add(txt_bnro_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        tbl_busqueda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_busqueda);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 200));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Nombre");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 35, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("CI/RUC");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, -1, -1));

        btn_agreg_busq.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_busq.setText("Agregar");
        jPanel7.add(btn_agreg_busq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jPanel11.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 300));

        ventana_busqueda.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 330));

        ventana_transaccion.setTitle("VENTANA TRANSACCION");
        ventana_transaccion.setResizable(false);
        ventana_transaccion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_transaccion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_transaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_transaccion);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 250));

        btn_agreg_trans.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_trans.setText("Agregar");
        jPanel8.add(btn_agreg_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jPanel14.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 300));

        ventana_transaccion.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 330));

        ventana_saldo_cliente.setTitle("SALDOS CLIENTES");
        ventana_saldo_cliente.setResizable(false);
        ventana_saldo_cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_saldo_cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_saldo_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_saldo_cliente);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 680, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("PARA SELECCIONAR MAS DE  UNA FILA PULSE LA TECLA SHIFT");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, -1));

        btn_agreg_sal.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_sal.setText("Agregar");
        btn_agreg_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_salActionPerformed(evt);
            }
        });
        jPanel9.add(btn_agreg_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 265, -1, -1));

        jPanel15.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 300));

        ventana_saldo_cliente.getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 320));

        ventana_talonario.setTitle("BUSQUEDA TALONARIO");
        ventana_talonario.setResizable(false);
        ventana_talonario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_busq_talonario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_busq_talonario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_busq_talonario);

        jPanel18.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 220));

        btn_agreg_tal.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_tal.setText("Agregar");
        jPanel18.add(btn_agreg_tal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jPanel10.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 280));

        ventana_talonario.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        ventana_error.setTitle("VENTANA DE ERROR DEL SISTEMA");
        ventana_error.setResizable(false);
        ventana_error.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_error.setEditable(false);
        txt_error.setColumns(20);
        txt_error.setLineWrap(true);
        txt_error.setRows(5);
        txt_error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setViewportView(txt_error);

        jPanel17.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 250));

        btn_volver_err.setBackground(new java.awt.Color(255, 102, 0));
        btn_volver_err.setText("Volver");
        jPanel17.add(btn_volver_err, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 310));

        ventana_error.getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECIBOS(FORMRECIBO)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DATOS CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Sucursal:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tipo Comp:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cliente:(F9)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cobrador:(F9)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Moneda:");

        txt_nro_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_compActionPerformed(evt);
            }
        });
        txt_nro_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nro_compKeyTyped(evt);
            }
        });

        txt_cod_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_clienteKeyTyped(evt);
            }
        });

        txt_cod_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_monedaActionPerformed(evt);
            }
        });

        txt_desc_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_monedaActionPerformed(evt);
            }
        });

        lbl_serie_nro.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_serie_nro.setForeground(new java.awt.Color(204, 204, 0));
        lbl_serie_nro.setText("*");

        campo_obligatorio.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        campo_obligatorio.setForeground(new java.awt.Color(204, 204, 0));
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS *");

        lbl_fec_comp.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_fec_comp.setForeground(new java.awt.Color(204, 204, 0));
        lbl_fec_comp.setText("*");

        lbl_cod_cliente.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod_cliente.setForeground(new java.awt.Color(204, 204, 0));
        lbl_cod_cliente.setText("*");

        lbl_cod_moneda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod_moneda.setForeground(new java.awt.Color(204, 204, 0));
        lbl_cod_moneda.setText("*");

        txt_ser_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ser_compActionPerformed(evt);
            }
        });
        txt_ser_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ser_compKeyTyped(evt);
            }
        });

        btn_suc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_suc.setToolTipText("Buscar");

        btn_mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_mon.setToolTipText("Buscar");

        btn_tip_comp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_tip_comp.setToolTipText("Buscar");

        btn_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_cli.setToolTipText("Buscar");

        btn_cob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_cob.setToolTipText("Buscar");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(61, 61, 61)
                        .addComponent(txt_cod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_desc_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(txt_cod_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_suc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_desc_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(txt_cod_tipo_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_tip_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_ser_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_nro_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lbl_serie_nro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(txt_fecha_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_fec_comp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(txt_cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_desc_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_cod_cliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(txt_cod_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_cob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_desc_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(57, 57, 57)
                        .addComponent(txt_cod_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txt_desc_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_cod_moneda)
                        .addGap(45, 45, 45)
                        .addComponent(campo_obligatorio))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(txt_fecha_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btn_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(txt_desc_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lbl_cod_moneda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(campo_obligatorio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btn_cob, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(txt_desc_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btn_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(txt_desc_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbl_cod_cliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_tip_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_ser_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_nro_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbl_serie_nro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbl_fec_comp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_desc_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_suc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_desc_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel14)
                            .addComponent(txt_cod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txt_cod_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txt_cod_tipo_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(txt_cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(txt_cod_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(txt_cod_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "TIPO TRANSACCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Transaccion:");

        txt_sub_tipo_transaccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sub_tipo_transaccionKeyTyped(evt);
            }
        });

        txt_total_comprobante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_comprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_comprobanteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Total Recibo:");

        btn_trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_trans.setToolTipText("Buscar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Limpar Detalle");

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17_2.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        tbl_comprobante = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_comprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_comprobante);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addComponent(txt_sub_tipo_transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txt_desc_tipo_transac, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addComponent(txt_total_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel7)
                                .addComponent(txt_sub_tipo_transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel15)
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(txt_total_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_desc_tipo_transac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 870, 270));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setBackground(new java.awt.Color(0, 51, 255));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyPressed(evt);
            }
        });
        jPanel19.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 80, 25));

        btn_guardar.setBackground(new java.awt.Color(0, 51, 255));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Confirmar");
        btn_guardar.setToolTipText("GRABAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        btn_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_guardarKeyPressed(evt);
            }
        });
        jPanel19.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 10, 105, 25));

        btn_actualizar.setBackground(new java.awt.Color(0, 51, 255));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Editar");
        btn_actualizar.setToolTipText("Modificar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel19.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 10, 80, 25));

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel19.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 10, 95, 25));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel19.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 10, 100, 25));

        btn_busqueda.setBackground(new java.awt.Color(0, 153, 0));
        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        btn_busqueda.setText("Buscar");
        btn_busqueda.setToolTipText("Buscar");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });
        jPanel19.add(btn_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 10, 85, 25));

        btn_ejecutar.setBackground(new java.awt.Color(0, 153, 0));
        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.setToolTipText("Ejecutar");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jPanel19.add(btn_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 10, 95, 25));

        btn_error.setBackground(new java.awt.Color(255, 102, 0));
        btn_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_error.setForeground(new java.awt.Color(255, 255, 255));
        btn_error.setText("Ver Error");
        btn_error.setToolTipText("Ver Error");
        btn_error.setFocusable(false);
        btn_error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_error.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_errorActionPerformed(evt);
            }
        });
        jPanel19.add(btn_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 10, 100, 25));

        btn_salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel19.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 10, 70, 25));

        jPanel4.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 870, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nro_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_compActionPerformed

    private void txt_cod_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_monedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_monedaActionPerformed

    private void txt_desc_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_monedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_monedaActionPerformed

    private void txt_total_comprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_comprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_comprobanteActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_bnro_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bnro_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bnro_documentoActionPerformed

    private void btn_agreg_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_salActionPerformed

    private void btn_agreg_cobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_cobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_cobActionPerformed

    private void txt_ser_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ser_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ser_compActionPerformed

    private void txt_ser_compKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ser_compKeyTyped
        int num=2;
        if(txt_ser_comp.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_txt_ser_compKeyTyped

    private void txt_nro_compKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_compKeyTyped
        char tecla;
        int num=15;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_nro_comp.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nro_compKeyTyped

    private void txt_sub_tipo_transaccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sub_tipo_transaccionKeyTyped
        char tecla;
        int num=2;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_sub_tipo_transaccion.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_sub_tipo_transaccionKeyTyped

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyPressed

    }//GEN-LAST:event_btn_nuevoKeyPressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_guardarKeyPressed

    }//GEN-LAST:event_btn_guardarKeyPressed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_errorActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_cod_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_clienteKeyTyped
        char tecla;
        int num=10;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_cliente.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_clienteKeyTyped

    private void txt_bnro_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bnro_documentoKeyTyped
        char tecla;
        int num=10;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_bnro_documento.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_bnro_documentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMRECIBO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMRECIBO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMRECIBO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMRECIBO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMRECIBO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_agreg_busq;
    public javax.swing.JButton btn_agreg_cob;
    public javax.swing.JButton btn_agreg_moneda;
    public javax.swing.JButton btn_agreg_sal;
    public javax.swing.JButton btn_agreg_tal;
    public javax.swing.JButton btn_agreg_trans;
    public javax.swing.JButton btn_busqueda;
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_cli;
    public javax.swing.JButton btn_cob;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_error;
    public javax.swing.JButton btn_guardar;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_mon;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_suc;
    public javax.swing.JButton btn_tip_comp;
    public javax.swing.JButton btn_trans;
    public javax.swing.JButton btn_volver_err;
    public javax.swing.JLabel campo_obligatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JLabel lbl_cod_cliente;
    public javax.swing.JLabel lbl_cod_moneda;
    public javax.swing.JLabel lbl_fec_comp;
    public javax.swing.JLabel lbl_serie_nro;
    public javax.swing.JTable tbl_bcobrador;
    public javax.swing.JTable tbl_bmoneda;
    public javax.swing.JTable tbl_busq_talonario;
    public javax.swing.JTable tbl_busqueda;
    public javax.swing.JTable tbl_comprobante;
    public javax.swing.JTable tbl_saldo_cliente;
    public javax.swing.JTable tbl_transaccion;
    public javax.swing.JTextField txt_bnomb_cliente;
    public javax.swing.JTextField txt_bnro_documento;
    public javax.swing.JTextField txt_cod_cliente;
    public javax.swing.JTextField txt_cod_cobrador;
    public javax.swing.JTextField txt_cod_moneda;
    public javax.swing.JTextField txt_cod_sucursal;
    public javax.swing.JTextField txt_cod_tipo_comp;
    public javax.swing.JTextField txt_cod_usuario;
    public javax.swing.JTextField txt_desc_cliente;
    public javax.swing.JTextField txt_desc_cobrador;
    public javax.swing.JTextField txt_desc_moneda;
    public javax.swing.JTextField txt_desc_sucursal;
    public javax.swing.JTextField txt_desc_tipo_transac;
    public javax.swing.JTextField txt_desc_usuario;
    public javax.swing.JTextArea txt_error;
    public com.toedter.calendar.JDateChooser txt_fecha_comp;
    public javax.swing.JTextField txt_nro_comp;
    public javax.swing.JTextField txt_ser_comp;
    public javax.swing.JTextField txt_sub_tipo_transaccion;
    public javax.swing.JTextField txt_total_comprobante;
    private javax.swing.JDialog ventana_busqueda;
    private javax.swing.JDialog ventana_cobrador;
    private javax.swing.JDialog ventana_error;
    private javax.swing.JDialog ventana_moneda;
    private javax.swing.JDialog ventana_saldo_cliente;
    private javax.swing.JDialog ventana_talonario;
    private javax.swing.JDialog ventana_transaccion;
    // End of variables declaration//GEN-END:variables

    public void habilita_campos() {
        txt_cod_cliente.setEditable(true);
        txt_cod_cobrador.setEditable(true);
        txt_cod_moneda.setEditable(true);
        //txt_cod_sucursal.setEditable(true);
        //txt_cod_tipo_comp.setEditable(true);
        txt_desc_cliente.setEditable(true);
        txt_desc_cobrador.setEditable(true);
        txt_desc_moneda.setEditable(true);
        //txt_desc_sucursal.setEditable(true);
        txt_desc_tipo_transac.setEditable(true);
        txt_fecha_comp.setEnabled(true);
        txt_nro_comp.setEditable(true);
        txt_ser_comp.setEditable(true);
        txt_sub_tipo_transaccion.setEditable(true);
        btn_suc.setEnabled(true);
        btn_tip_comp.setEnabled(true);
        btn_cli.setEnabled(true);
        btn_cob.setEnabled(true);
        btn_mon.setEnabled(true);
        btn_trans.setEnabled(true);
        txt_cod_cliente.requestFocus();
    }

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_fecha();
        ocultar_labeles();
    }

    private void bloquea_campos() {
        txt_cod_cliente.setEditable(false);
        txt_cod_cobrador.setEditable(false);
        txt_cod_moneda.setEditable(false);
        txt_cod_sucursal.setEditable(false);
        txt_cod_usuario.setEditable(false);
        txt_desc_usuario.setEditable(false);
        txt_cod_tipo_comp.setEditable(false);
        txt_desc_cliente.setEditable(false);
        txt_desc_cobrador.setEditable(false);
        txt_desc_moneda.setEditable(false);
        txt_desc_sucursal.setEditable(false);
        txt_desc_tipo_transac.setEditable(false);
        txt_fecha_comp.setEnabled(false);
        txt_nro_comp.setEditable(false);
        txt_ser_comp.setEditable(false);
        txt_sub_tipo_transaccion.setEditable(false);
        txt_total_comprobante.setEditable(false);
        btn_suc.setEnabled(false);
        btn_tip_comp.setEnabled(false);
        btn_cli.setEnabled(false);
        btn_cob.setEnabled(false);
        btn_mon.setEnabled(false);
        btn_trans.setEnabled(false);
    }

    private void bloquea_botones() {
        btn_actualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_ejecutar.setEnabled(false);
        btn_error.setEnabled(false);
        btn_busqueda.setEnabled(true);
        btn_nuevo.setEnabled(true);
        btn_nuevo.requestFocus();
    }

    private void carga_fecha() {
        try {
        Date hoy = new Date();
        Date fecha=null;
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
        String fechaact = formatofecha.format(hoy);
        fecha=formatofecha.parse(fechaact);
        txt_fecha_comp.setDate(fecha);
        } catch (ParseException ex) {
             Logger.getLogger(controlador_persona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void ventana_busqueda(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_busqueda.setVisible(true);
        ventana_busqueda.setSize(420,350);
        ventana_busqueda.setLocationRelativeTo(bus);
        txt_bnro_documento.setText("");
        txt_bnomb_cliente.setText("%%");
    }
    public void cerrar_ventana_busqueda(){
        ventana_busqueda.dispose();
    }
    public void ventana_cobrador(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_cobrador.setVisible(true);
        ventana_cobrador.setSize(420, 410);
        ventana_cobrador.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_cobrador(){
        ventana_cobrador.dispose();
    }
    public void ventana_moneda(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_moneda.setVisible(true);
        ventana_moneda.setSize(420,200);
        ventana_moneda.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_moneda(){
        ventana_moneda.dispose();
    }
    public void ventana_transaccion(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_transaccion.setVisible(true);
        ventana_transaccion.setSize(420,350);
        ventana_transaccion.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_transaccion(){
        ventana_transaccion.dispose();
    }
    public void ventana_saldo_cliente(){
      FORMFACTUR bus = new FORMFACTUR();
        ventana_saldo_cliente.setVisible(true);
        ventana_saldo_cliente.setSize(720,345);
        ventana_saldo_cliente.setLocationRelativeTo(bus);  
    }
    public void cerrar_ventana_saldo_cliente(){
        ventana_saldo_cliente.dispose();
    }
    public void ventana_talonario() {
        FORMFACTUR bus = new FORMFACTUR();
        ventana_talonario.setVisible(true);
        ventana_talonario.setSize(400, 323);
        ventana_talonario.setLocationRelativeTo(bus);
    }

    public void cerrar_ventana_talonario() {
        ventana_talonario.dispose();
    }
    public void ventana_error(){
        FORMFACCOM bus = new FORMFACCOM();
        ventana_error.setVisible(true);
        ventana_error.setSize(590,355);
        ventana_error.setLocationRelativeTo(bus);
    }
    public void cerrar_ventana_error(){
        ventana_error.dispose();
    }
    public void limpia_campos() {
        txt_cod_cliente.setText("");
        txt_cod_cobrador.setText("");
        txt_cod_moneda.setText("");
        txt_desc_cliente.setText("");
        txt_desc_cobrador.setText("");
        txt_desc_moneda.setText("");
        txt_desc_tipo_transac.setText("");
        txt_nro_comp.setText("");
        txt_ser_comp.setText("");
        txt_sub_tipo_transaccion.setText("");
        txt_total_comprobante.setText("");
    }

    private void ocultar_labeles() {
        lbl_serie_nro.setVisible(false);
        lbl_cod_cliente.setVisible(false);
        lbl_cod_moneda.setVisible(false);
        lbl_fec_comp.setVisible(false);
        campo_obligatorio.setVisible(false);
    }
    public void mostrar_campos_requeridos() {
        lbl_serie_nro.setVisible(true);
        lbl_cod_cliente.setVisible(true);
        lbl_cod_moneda.setVisible(true);
        lbl_fec_comp.setVisible(true);
        campo_obligatorio.setVisible(true);
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS * ");
        //
        lbl_serie_nro.setForeground(new Color(255,51,51));
        lbl_cod_cliente.setForeground(new Color(255,51,51));
        lbl_cod_moneda.setForeground(new Color(255,51,51));
        lbl_fec_comp.setForeground(new Color(255,51,51));
        campo_obligatorio.setForeground(new Color(255,51,51));
    }
    public void mostrar_campos_busqueda() {
        lbl_serie_nro.setVisible(true);
        campo_obligatorio.setVisible(true);
        campo_obligatorio.setText("CAMPOS DE BUSQUEDA * ");
        //
        lbl_serie_nro.setForeground(new Color(255,51,51));
        campo_obligatorio.setForeground(new Color(255,51,51));
    }
}
