
package vista;

import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JONY
 */
public class FORMCONDVE extends javax.swing.JFrame {

    
    public FORMCONDVE() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_condicion();
    }
private void cerrar_ventan_condicion() {
        setDefaultCloseOperation(FORMCONDVE.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanacondicion();
            }
        });
    }
   public void cerrar_ventanacondicion(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cod_condicion = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_nro_cuota = new javax.swing.JTextField();
        txt_dia_inicial = new javax.swing.JTextField();
        txt_plazo = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_condicion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONDICIONES VENTAS(FORMCONDVE)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);

        btnnuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnnuevo.setToolTipText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        btnnuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnnuevoKeyPressed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GRABAR");
        jToolBar1.add(btnguardar);

        btnactualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setToolTipText("Modificar");
        jToolBar1.add(btnactualizar);

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        jToolBar1.add(btneliminar);

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncancelar);

        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btn_busqueda.setToolTipText("Buscar");
        jToolBar1.add(btn_busqueda);

        btn_imprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btn_imprimir.setToolTipText("Imprimir");
        jToolBar1.add(btn_imprimir);

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        btn_salir.setToolTipText("Salir");
        jToolBar1.add(btn_salir);

        jPanel3.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 361, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Cod Condicion:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Descripcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 41, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Numero Cuota: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 67, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Dial Inicial:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 92, 76, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Plazo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 118, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 144, -1, -1));

        txt_cod_condicion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cod_condicionFocusLost(evt);
            }
        });
        txt_cod_condicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_condicionActionPerformed(evt);
            }
        });
        txt_cod_condicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_condicionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 12, 70, -1));

        txt_descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_descripcionFocusLost(evt);
            }
        });
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        txt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 38, 200, -1));

        txt_nro_cuota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nro_cuotaFocusLost(evt);
            }
        });
        txt_nro_cuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_cuotaActionPerformed(evt);
            }
        });
        txt_nro_cuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nro_cuotaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nro_cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 64, 70, -1));

        txt_dia_inicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dia_inicialFocusLost(evt);
            }
        });
        txt_dia_inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dia_inicialActionPerformed(evt);
            }
        });
        txt_dia_inicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dia_inicialKeyTyped(evt);
            }
        });
        jPanel1.add(txt_dia_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 89, 70, -1));

        txt_plazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_plazoActionPerformed(evt);
            }
        });
        txt_plazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_plazoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 115, 70, -1));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 141, 200, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 580, 170));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_condicion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_condicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_condicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_condicionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_condicion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 240));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 580, 260));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        habilita_campos();
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnnuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnnuevoKeyPressed
       habilita_campos();
       btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoKeyPressed

    private void txt_cod_condicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_condicionKeyTyped
        char tecla;
        int num=2;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_condicion.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_condicionKeyTyped

    private void txt_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionKeyTyped
        int num=50;
        if(txt_descripcion.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_descripcionKeyTyped

    private void txt_nro_cuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_cuotaKeyTyped
        char tecla;
        int num=2;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_nro_cuota.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nro_cuotaKeyTyped

    private void txt_dia_inicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dia_inicialKeyTyped
        char tecla;
        int num=1;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_dia_inicial.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_dia_inicialKeyTyped

    private void txt_plazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_plazoKeyTyped
        char tecla;
        int num=2;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_plazo.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_plazoKeyTyped

    private void txt_cod_condicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_condicionActionPerformed
        if (txt_cod_condicion.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Debe ingresar un codigo para continuar","Mensaje del sistema",JOptionPane.WARNING_MESSAGE);
       }else{
          txt_descripcion.requestFocus();
       }
    }//GEN-LAST:event_txt_cod_condicionActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        if (txt_descripcion.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Debe ingresar la descripcion para continuar","Mensaje del sistema",JOptionPane.WARNING_MESSAGE);
       }else{
          txt_nro_cuota.requestFocus();
       }
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void txt_dia_inicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dia_inicialActionPerformed
        if (txt_dia_inicial.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Debe ingresar el dia para continuar","Mensaje del sistema",JOptionPane.WARNING_MESSAGE);
       }else{
          txt_plazo.requestFocus();
       }
    }//GEN-LAST:event_txt_dia_inicialActionPerformed

    private void txt_plazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_plazoActionPerformed
        if (txt_plazo.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Debe ingresar el plazo para continuar","Mensaje del sistema",JOptionPane.WARNING_MESSAGE);
       }else{
          cmb_estado.requestFocus();
       }
    }//GEN-LAST:event_txt_plazoActionPerformed

    private void txt_nro_cuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_cuotaActionPerformed
        if (txt_nro_cuota.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Debe ingresar la cantidad de cuota para continuar","Mensaje del sistema",JOptionPane.WARNING_MESSAGE);
       }else{
          txt_dia_inicial.requestFocus();
       }
    }//GEN-LAST:event_txt_nro_cuotaActionPerformed

    private void txt_cod_condicionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cod_condicionFocusLost
        
    }//GEN-LAST:event_txt_cod_condicionFocusLost

    private void txt_descripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_descripcionFocusLost
       
    }//GEN-LAST:event_txt_descripcionFocusLost

    private void txt_nro_cuotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nro_cuotaFocusLost
        
    }//GEN-LAST:event_txt_nro_cuotaFocusLost

    private void txt_dia_inicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dia_inicialFocusLost
        
    }//GEN-LAST:event_txt_dia_inicialFocusLost

    private void tbl_condicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_condicionMouseClicked
        btneliminar.setEnabled(true);
    }//GEN-LAST:event_tbl_condicionMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMCONDVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMCONDVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMCONDVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMCONDVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMCONDVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_imprimir;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    public javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tbl_condicion;
    public javax.swing.JTextField txt_cod_condicion;
    public javax.swing.JTextField txt_descripcion;
    public javax.swing.JTextField txt_dia_inicial;
    public javax.swing.JTextField txt_nro_cuota;
    public javax.swing.JTextField txt_plazo;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_combobox();
    }

    private void bloquea_campos() {
        txt_cod_condicion.setEditable(false);
        txt_descripcion.setEditable(false);
        txt_dia_inicial.setEditable(false);
        txt_nro_cuota.setEditable(false);
        txt_plazo.setEditable(false);
        cmb_estado.setEnabled(false);
    }

    private void bloquea_botones() {
      btn_imprimir.setEnabled(false);
      btnactualizar.setEnabled(false);
      btneliminar.setEnabled(false);
      btnguardar.setEnabled(false);  
      btnnuevo.requestFocus();
    }

    private void carga_combobox() {
        Object tpd[] = new Object[2];
        tpd[0] ="ACTIVO";
        tpd[1] ="INACTIVO";
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(tpd);
        this.cmb_estado.setModel(dcb);
        //cmb_estado.addItem("Seleccione Opcion");
        //String std = "Seleccione Opcion";
        this.cmb_estado.setSelectedItem("ACTIVO");
    }

    public void habilita_campos() {
        txt_cod_condicion.setEditable(true);
        txt_descripcion.setEditable(true);
        txt_dia_inicial.setEditable(true);
        txt_nro_cuota.setEditable(true);
        txt_plazo.setEditable(true);
        cmb_estado.setEnabled(true);  
        txt_cod_condicion.requestFocus();
    }

    public void limpia_campos() {
        txt_cod_condicion.setText("");
        txt_descripcion.setText("");
        txt_dia_inicial.setText("");
        txt_nro_cuota.setText("");
        txt_plazo.setText("");
    }
}
