package vista;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan.torres
 */
public class FORMFORMPA extends javax.swing.JFrame {

    /**
     * Creates new form FORMFORMPA
     */
    public FORMFORMPA() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_pago();
    }
public void cerrar_ventan_pago() {
        setDefaultCloseOperation(FORMFORMPA.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrar_ventanapago();
            }
        });
    }

    public void cerrar_ventanapago() {
        int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opc == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_proveedor = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txt_bcod_prov = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_bdesc_prov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bprov = new javax.swing.JTable();
        btn_agreg_prov = new javax.swing.JButton();
        ventana_compr_prov = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_bcomp_prov = new javax.swing.JTable();
        btn_agreg_comp_prov = new javax.swing.JButton();
        ventana_transacc = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txt_bcod_sub_tip = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_bsub_tipo = new javax.swing.JTable();
        btn_agreg_sub_trans = new javax.swing.JButton();
        ventana_persona = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_bperso = new javax.swing.JTable();
        txt_bcod_pers = new javax.swing.JTextField();
        txt_bnom_pers = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_agreg_pers = new javax.swing.JButton();
        ventana_error = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_error = new javax.swing.JTextArea();
        btn_volver_err = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_nuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_error = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_tipo_mov_caja = new javax.swing.JTextField();
        txt_ser_mov_caja = new javax.swing.JTextField();
        txt_nro_mov_caja = new javax.swing.JTextField();
        txt_fecha_mov = new com.toedter.calendar.JDateChooser();
        txt_cod_proveedor = new javax.swing.JTextField();
        txt_desc_proveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_comprobante = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_total_comprobante = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        lbl_nro = new javax.swing.JLabel();
        lbl_serie = new javax.swing.JLabel();
        campo_obligatorio = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_sub_tipo_trans_comp = new javax.swing.JTextField();
        txt_desc_sub_tipo_trans_comp = new javax.swing.JTextField();
        btn_sub_tip1 = new javax.swing.JButton();
        btn_prov = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_sub_tipo_transacc = new javax.swing.JTextField();
        txt_desc_sub_tipo_transacc = new javax.swing.JTextField();
        txt_cod_pers_jurid = new javax.swing.JTextField();
        txt_desc_pers_jurid = new javax.swing.JTextField();
        txt_nro_valor = new javax.swing.JTextField();
        txt_nro_cuenta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cobro = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        btn_limpiar_cobro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_total_importe = new javax.swing.JTextField();
        btn_sub_tip2 = new javax.swing.JButton();
        btn_pers = new javax.swing.JButton();
        txt_importe = new javax.swing.JTextField();
        txt_cod_usuario = new javax.swing.JTextField();
        txt_cod_sucursal = new javax.swing.JTextField();
        txt_desc_usuario = new javax.swing.JTextField();
        txt_desc_suscursal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        ventana_proveedor.setTitle("Busqueda Proveedor");
        ventana_proveedor.setResizable(false);
        ventana_proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(txt_bcod_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("R.U.C/CI");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txt_bdesc_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bdesc_provActionPerformed(evt);
            }
        });
        jPanel10.add(txt_bdesc_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 210, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Nombre:");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        tbl_bprov = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bprov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_bprov);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 410, 270));

        btn_agreg_prov.setText("Agregar");
        jPanel10.add(btn_agreg_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 380));

        ventana_proveedor.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        ventana_compr_prov.setResizable(false);
        ventana_compr_prov.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 0));
        jLabel16.setText("PARA SELECCIONAR MAS DE  UNA FILA PULSE LA TECLA SHIFT");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 410, -1));

        tbl_bcomp_prov = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcomp_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_bcomp_prov);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 240));

        btn_agreg_comp_prov.setText("Agregar");
        btn_agreg_comp_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_comp_provActionPerformed(evt);
            }
        });
        jPanel12.add(btn_agreg_comp_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 320));

        ventana_compr_prov.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        ventana_transacc.setTitle("Tipo Transaccion");
        ventana_transacc.setResizable(false);
        ventana_transacc.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(txt_bcod_sub_tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, 20));

        tbl_bsub_tipo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bsub_tipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_bsub_tipo);

        jPanel11.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 170));

        btn_agreg_sub_trans.setText("Agregar");
        btn_agreg_sub_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_sub_transActionPerformed(evt);
            }
        });
        jPanel11.add(btn_agreg_sub_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 220));

        ventana_transacc.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 240));

        ventana_persona.setTitle("Banco");
        ventana_persona.setResizable(false);
        ventana_persona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bperso = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bperso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_bperso);

        jPanel13.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 350, 210));
        jPanel13.add(txt_bcod_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, -1));
        jPanel13.add(txt_bnom_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 230, -1));

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 0));
        jLabel20.setText("Nombre:");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        btn_agreg_pers.setText("Agregar");
        jPanel13.add(btn_agreg_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 320));

        ventana_persona.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 340));

        ventana_error.setTitle("VENTANA DE ERROR DEL SISTEMA");
        ventana_error.setResizable(false);
        ventana_error.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_error.setEditable(false);
        txt_error.setColumns(20);
        txt_error.setLineWrap(true);
        txt_error.setRows(5);
        txt_error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane7.setViewportView(txt_error);

        jPanel16.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 250));

        btn_volver_err.setText("Volver");
        jPanel16.add(btn_volver_err, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 310));

        ventana_error.getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORMA DE PAGO(FORMFORMPA)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);

        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyPressed(evt);
            }
        });
        jToolBar1.add(btn_nuevo);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("GRABAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btnactualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setToolTipText("Modificar");
        jToolBar1.add(btnactualizar);

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncancelar);

        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btn_busqueda.setToolTipText("Buscar");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_busqueda);

        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.png"))); // NOI18N
        btn_ejecutar.setToolTipText("Buscar");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ejecutar);

        btn_imprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btn_imprimir.setToolTipText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_imprimir);

        btn_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_error.png"))); // NOI18N
        btn_error.setToolTipText("Ver Error");
        btn_error.setFocusable(false);
        btn_error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_error.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_errorActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_error);

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        btn_ant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        btn_ant.setToolTipText("Anterior reg");
        btn_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ant);

        btn_sig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        btn_sig.setToolTipText("Sigiente reg");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_sig);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 54));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tipo_mov_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipo_mov_cajaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tipo_mov_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 30, 50, -1));
        jPanel1.add(txt_ser_mov_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 120, 50, -1));

        txt_nro_mov_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_mov_cajaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nro_mov_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 75, 50, -1));
        jPanel1.add(txt_fecha_mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 170, 120, -1));
        jPanel1.add(txt_cod_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 210, 50, -1));

        txt_desc_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_proveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_desc_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Tipo Mov Caja:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Serie:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Nro Nov Caja:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Cod Proveedor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_comprobante = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_comprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_comprobante.setPreferredSize(new java.awt.Dimension(300, 65));
        jScrollPane1.setViewportView(tbl_comprobante);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 125));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("Limpar Detalle");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17_2.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel9.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 145, 40, 25));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 51));
        jLabel19.setText("TOTAL COMP:");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 150, -1, -1));

        txt_total_comprobante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel9.add(txt_total_comprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 145, 150, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 580, 180));

        lbl_tipo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(204, 204, 0));
        lbl_tipo.setText("*");
        jPanel1.add(lbl_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lbl_nro.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_nro.setForeground(new java.awt.Color(204, 204, 0));
        lbl_nro.setText("*");
        jPanel1.add(lbl_nro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 75, -1, -1));

        lbl_serie.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_serie.setForeground(new java.awt.Color(204, 204, 0));
        lbl_serie.setText("*");
        jPanel1.add(lbl_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        campo_obligatorio.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        campo_obligatorio.setForeground(new java.awt.Color(204, 204, 0));
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS *");
        jPanel1.add(campo_obligatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 0));
        jLabel22.setText("Sub Tip Trans Comp:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txt_sub_tipo_trans_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sub_tipo_trans_compActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sub_tipo_trans_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 240, 50, -1));

        txt_desc_sub_tipo_trans_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_sub_tipo_trans_compActionPerformed(evt);
            }
        });
        jPanel1.add(txt_desc_sub_tipo_trans_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 250, -1));

        btn_sub_tip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_sub_tip1.setToolTipText("Buscar");
        jPanel1.add(btn_sub_tip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 25, 20));

        btn_prov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_prov.setToolTipText("Buscar");
        jPanel1.add(btn_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 25, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1000, 270));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DETALLE DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_sub_tipo_transacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sub_tipo_transaccActionPerformed(evt);
            }
        });
        jPanel3.add(txt_sub_tipo_transacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 20, 50, -1));

        txt_desc_sub_tipo_transacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_sub_tipo_transaccActionPerformed(evt);
            }
        });
        jPanel3.add(txt_desc_sub_tipo_transacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 210, -1));
        jPanel3.add(txt_cod_pers_jurid, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 50, 50, -1));
        jPanel3.add(txt_desc_pers_jurid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 210, -1));
        jPanel3.add(txt_nro_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 80, 150, -1));
        jPanel3.add(txt_nro_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 110, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("Sub Tip Trans Cobr:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("Entidad:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("Nro/Valor:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("Nro/Cuenta:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("Importe:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_cobro = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_cobro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cobro.setName(""); // NOI18N
        tbl_cobro.setPreferredSize(new java.awt.Dimension(300, 65));
        jScrollPane2.setViewportView(tbl_cobro);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 104));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setText("Limpar Detalle");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btn_limpiar_cobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17_2.png"))); // NOI18N
        btn_limpiar_cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_cobroActionPerformed(evt);
            }
        });
        jPanel8.add(btn_limpiar_cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("TOTAL IMPO:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        txt_total_importe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(txt_total_importe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 150, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 15, 530, 150));

        btn_sub_tip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_sub_tip2.setToolTipText("Buscar");
        jPanel3.add(btn_sub_tip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 25, 20));

        btn_pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_pers.setToolTipText("Buscar");
        jPanel3.add(btn_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 25, 20));

        txt_importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_importeKeyTyped(evt);
            }
        });
        jPanel3.add(txt_importe, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 150, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1000, 180));

        txt_cod_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 70, -1));
        jPanel2.add(txt_cod_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 35, 70, -1));

        txt_desc_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_desc_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 10, 250, -1));
        jPanel2.add(txt_desc_suscursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 35, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Usuario:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Sucursal:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 35, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyPressed

    }//GEN-LAST:event_btn_nuevoKeyPressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

    }//GEN-LAST:event_btncancelarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed

        //imprimir_comprobante();
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antActionPerformed

    }//GEN-LAST:event_btn_antActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed

    }//GEN-LAST:event_btn_sigActionPerformed

    private void txt_tipo_mov_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipo_mov_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipo_mov_cajaActionPerformed

    private void txt_nro_mov_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_mov_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_mov_cajaActionPerformed

    private void txt_desc_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_proveedorActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_sub_tipo_transaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sub_tipo_transaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sub_tipo_transaccActionPerformed

    private void txt_desc_sub_tipo_transaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_sub_tipo_transaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_sub_tipo_transaccActionPerformed

    private void btn_limpiar_cobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_cobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiar_cobroActionPerformed

    private void txt_cod_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_usuarioActionPerformed

    private void txt_desc_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_usuarioActionPerformed

    private void txt_bdesc_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bdesc_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bdesc_provActionPerformed

    private void btn_agreg_comp_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_comp_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_comp_provActionPerformed

    private void txt_sub_tipo_trans_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sub_tipo_trans_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sub_tipo_trans_compActionPerformed

    private void txt_desc_sub_tipo_trans_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_sub_tipo_trans_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_sub_tipo_trans_compActionPerformed

    private void btn_agreg_sub_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_sub_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_sub_transActionPerformed

    private void btn_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_errorActionPerformed

    private void txt_importeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_importeKeyTyped
        char tecla;
        int num = 15;
        tecla = evt.getKeyChar();
        //Validacion de solo numero o decimales
        if(((tecla < '0') || (tecla > '9')) && (tecla != KeyEvent.VK_BACK_SPACE) && (tecla !='.')){
            evt.consume();
            getToolkit().beep();
        }
        if (txt_importe.getText().length() >= num) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_importeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMFORMPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMFORMPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMFORMPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMFORMPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMFORMPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agreg_comp_prov;
    public javax.swing.JButton btn_agreg_pers;
    public javax.swing.JButton btn_agreg_prov;
    public javax.swing.JButton btn_agreg_sub_trans;
    public javax.swing.JButton btn_ant;
    public javax.swing.JButton btn_busqueda;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JButton btn_error;
    public javax.swing.JButton btn_imprimir;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_limpiar_cobro;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_pers;
    public javax.swing.JButton btn_prov;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_sig;
    public javax.swing.JButton btn_sub_tip1;
    public javax.swing.JButton btn_sub_tip2;
    public javax.swing.JButton btn_volver_err;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JLabel campo_obligatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JLabel lbl_nro;
    public javax.swing.JLabel lbl_serie;
    public javax.swing.JLabel lbl_tipo;
    public javax.swing.JTable tbl_bcomp_prov;
    public javax.swing.JTable tbl_bperso;
    public javax.swing.JTable tbl_bprov;
    public javax.swing.JTable tbl_bsub_tipo;
    public javax.swing.JTable tbl_cobro;
    public javax.swing.JTable tbl_comprobante;
    public javax.swing.JTextField txt_bcod_pers;
    public javax.swing.JTextField txt_bcod_prov;
    public javax.swing.JTextField txt_bcod_sub_tip;
    public javax.swing.JTextField txt_bdesc_prov;
    public javax.swing.JTextField txt_bnom_pers;
    public javax.swing.JTextField txt_cod_pers_jurid;
    public javax.swing.JTextField txt_cod_proveedor;
    public javax.swing.JTextField txt_cod_sucursal;
    public javax.swing.JTextField txt_cod_usuario;
    public javax.swing.JTextField txt_desc_pers_jurid;
    public javax.swing.JTextField txt_desc_proveedor;
    public javax.swing.JTextField txt_desc_sub_tipo_trans_comp;
    public javax.swing.JTextField txt_desc_sub_tipo_transacc;
    public javax.swing.JTextField txt_desc_suscursal;
    public javax.swing.JTextField txt_desc_usuario;
    public javax.swing.JTextArea txt_error;
    public com.toedter.calendar.JDateChooser txt_fecha_mov;
    public javax.swing.JTextField txt_importe;
    public javax.swing.JTextField txt_nro_cuenta;
    public javax.swing.JTextField txt_nro_mov_caja;
    public javax.swing.JTextField txt_nro_valor;
    public javax.swing.JTextField txt_ser_mov_caja;
    public javax.swing.JTextField txt_sub_tipo_trans_comp;
    public javax.swing.JTextField txt_sub_tipo_transacc;
    public javax.swing.JTextField txt_tipo_mov_caja;
    public javax.swing.JTextField txt_total_comprobante;
    public javax.swing.JTextField txt_total_importe;
    private javax.swing.JDialog ventana_compr_prov;
    private javax.swing.JDialog ventana_error;
    private javax.swing.JDialog ventana_persona;
    private javax.swing.JDialog ventana_proveedor;
    private javax.swing.JDialog ventana_transacc;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_fecha();
        ocultar_labeles();
    }
    private void bloquea_campos() {
        txt_bcod_pers.setVisible(false);
        txt_cod_proveedor.setEditable(false);
        txt_cod_pers_jurid.setEditable(false);
        txt_cod_sucursal.setEditable(false);
        txt_cod_usuario.setEditable(false);
        txt_desc_proveedor.setEditable(false);
        txt_desc_pers_jurid.setEditable(false);
        txt_desc_sub_tipo_transacc.setEditable(false);
        txt_desc_suscursal.setEditable(false);
        txt_desc_usuario.setEditable(false);
        txt_fecha_mov.setEnabled(false);
        txt_nro_cuenta.setEditable(false);
        txt_nro_mov_caja.setEditable(false);
        txt_nro_valor.setEditable(false);
        txt_ser_mov_caja.setEditable(false);
        txt_sub_tipo_transacc.setEditable(false);
        txt_sub_tipo_trans_comp.setEditable(false);
        txt_desc_sub_tipo_trans_comp.setEditable(false);
        txt_tipo_mov_caja.setEditable(false);
        txt_total_comprobante.setEditable(false);
        txt_total_importe.setEditable(false);
        txt_importe.setEditable(false);
        btn_prov.setEnabled(false);
        btn_pers.setEnabled(false);
        btn_sub_tip1.setEnabled(false);
        btn_sub_tip2.setEnabled(false);
    }

    private void bloquea_botones() {
        btn_sig.setVisible(false);
        btn_ant.setVisible(false);
        txt_bcod_sub_tip.setVisible(false);
        btn_imprimir.setEnabled(false);
        btnactualizar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnguardar.setEnabled(false);
        btn_limpiar.setEnabled(false);
        btn_limpiar_cobro.setEnabled(false);
        btn_ejecutar.setEnabled(false);
        btn_busqueda.setEnabled(true);
        btn_nuevo.setEnabled(true);
        btn_nuevo.requestFocus();
    }

    private void carga_fecha()  {
        Date hoy = new Date();
        Date fecha = null;
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
        String fechaact = formatofecha.format(hoy);
        try {
            fecha = formatofecha.parse(fechaact);
        } catch (ParseException ex) {
            Logger.getLogger(FORMFORMPA.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_fecha_mov.setDate(fecha);
    }

    public void habilita_campos() {
        txt_cod_proveedor.setEditable(true);
        txt_cod_pers_jurid.setEditable(true);
        txt_cod_sucursal.setEditable(true);
        txt_cod_usuario.setEditable(true);
        txt_desc_proveedor.setEditable(true);
        txt_desc_pers_jurid.setEditable(true);
        txt_desc_sub_tipo_transacc.setEditable(true);
        txt_desc_suscursal.setEditable(true);
        txt_desc_usuario.setEditable(true);
        txt_fecha_mov.setEnabled(true);
        txt_nro_cuenta.setEditable(true);
        txt_nro_mov_caja.setEditable(true);
        txt_nro_valor.setEditable(true);
        txt_ser_mov_caja.setEditable(true);
        txt_sub_tipo_transacc.setEditable(true);
        txt_tipo_mov_caja.setEditable(true);
        txt_total_comprobante.setEditable(true);
        txt_total_importe.setEditable(true);
        txt_importe.setEditable(true);
        btn_prov.setEnabled(true);
        btn_pers.setEnabled(true);
        btn_sub_tip1.setEnabled(true);
        btn_sub_tip2.setEnabled(true);
        txt_cod_proveedor.requestFocus();
    }
    public void limpia_campos() {
        txt_cod_proveedor.setText("");
        txt_cod_pers_jurid.setText("");
        txt_desc_proveedor.setText("");
        txt_desc_pers_jurid.setText("");
        txt_desc_sub_tipo_transacc.setText("");
        txt_nro_cuenta.setText("");
        txt_nro_valor.setText("");
        txt_sub_tipo_transacc.setText("");
        txt_sub_tipo_trans_comp.setText("");
        txt_desc_sub_tipo_trans_comp.setText("");
        txt_total_comprobante.setText("");
        txt_total_importe.setText("");
        txt_importe.setText("");
        //txt_nro_mov_caja.setText("");
        txt_cod_proveedor.requestFocus();
    }

    private void ocultar_labeles() {
        lbl_nro.setVisible(false);
        lbl_serie.setVisible(false);
        lbl_tipo.setVisible(false);
        campo_obligatorio.setVisible(false);
    }
    public void ventana_proveedor() {
        FORMFORMPA bus = new FORMFORMPA();
        ventana_proveedor.setVisible(true);
        ventana_proveedor.setSize(455,425);
        ventana_proveedor.setLocationRelativeTo(bus);
        txt_bcod_prov.setText("");
        txt_bdesc_prov.setText("%");
    }
    public void cerrar_ventana_proveedor() {
        ventana_proveedor.dispose();
    }
    public void ventana_comprobante_proveedor() {
        FORMFORMPA bus = new FORMFORMPA();
        ventana_compr_prov.setVisible(true);
        ventana_compr_prov.setSize(700, 370);
        ventana_compr_prov.setLocationRelativeTo(bus);
    }

    public void cerrar_ventana_comprobante_proveedor() {
        ventana_compr_prov.dispose();
    }
    public void ventana_transaccion() {
        FORMFORMPA bus = new FORMFORMPA();
        ventana_transacc.setVisible(true);
        ventana_transacc.setSize(472, 270);
        ventana_transacc.setLocationRelativeTo(bus);
        txt_bcod_sub_tip.setText("");
    }

    public void cerrar_ventana_transaccion() {
        ventana_transacc.dispose();
    }
    public void ventana_persona() {
        FORMFORMPA bus = new FORMFORMPA();
        ventana_persona.setVisible(true);
        ventana_persona.setSize(400, 370);
        ventana_persona.setLocationRelativeTo(bus);
        txt_bcod_pers.setText("");
        txt_bnom_pers.setText("");
        txt_bnom_pers.setText("%");
    }

    public void cerrar_ventana_persona() {
        ventana_persona.dispose();
    }
    public void ventana_error(){
        FORMFORMPA bus = new FORMFORMPA();
        ventana_error.setVisible(true);
        ventana_error.setSize(590,355);
        ventana_error.setLocationRelativeTo(bus);
    }
    public void cerrar_ventana_error(){
        ventana_error.dispose();
    }
}
