
package vista;
import modeloBD.*;
import controlador.*;
import javax.swing.JOptionPane;
import vista.*;
/**
 *
 * @author JONY
 */
public class FORMMENUPR extends javax.swing.JFrame {

    /**
     * Creates new form Form_menuprincipal
     */
    public FORMMENUPR() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        cerrar_ventan_menu();
    }
private void cerrar_ventan_menu() {
        setDefaultCloseOperation(FORMMENUPR.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanamenu();
            }
        });
    }
   private void cerrar_ventanamenu(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   System.exit(0);
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_bienvenida = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_sucursal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        modulo_ajuste = new javax.swing.JMenu();
        FORMACCGRU = new javax.swing.JMenuItem();
        Formusuari = new javax.swing.JMenuItem();
        FORMSERCOM = new javax.swing.JMenuItem();
        FORMTALONA = new javax.swing.JMenuItem();
        FORMTALUSU = new javax.swing.JMenuItem();
        FORMBACKUP = new javax.swing.JMenuItem();
        FORMDESCON = new javax.swing.JMenuItem();
        FORMSALIR = new javax.swing.JMenuItem();
        modulo_ayuda = new javax.swing.JMenu();
        FORMCAMPAS = new javax.swing.JMenuItem();
        modulo_st = new javax.swing.JMenu();
        FORMARTICU = new javax.swing.JMenuItem();
        FORMAJUSTK = new javax.swing.JMenuItem();
        FORMCOEXAR = new javax.swing.JMenuItem();
        FORMCATART = new javax.swing.JMenuItem();
        FORMMARART = new javax.swing.JMenuItem();
        FORMUNMEAR = new javax.swing.JMenuItem();
        REP_STK = new javax.swing.JMenu();
        REPEXISART = new javax.swing.JMenuItem();
        modulo_cc = new javax.swing.JMenu();
        Formperson = new javax.swing.JMenuItem();
        FORMCLIENT = new javax.swing.JMenuItem();
        FORMRECIBO = new javax.swing.JMenuItem();
        FORMHBCJCO = new javax.swing.JMenuItem();
        FORMFORMCO = new javax.swing.JMenuItem();
        FORMCIECAJ = new javax.swing.JMenuItem();
        FORMCOSACL = new javax.swing.JMenuItem();
        REP_COB = new javax.swing.JMenu();
        REPEXTCLI1 = new javax.swing.JMenuItem();
        REPMOVCAJ1 = new javax.swing.JMenuItem();
        REPRECEMI1 = new javax.swing.JMenuItem();
        modulo_vt = new javax.swing.JMenu();
        FORMFACTUR = new javax.swing.JMenuItem();
        FORMCONDVE = new javax.swing.JMenuItem();
        FORMCNCMVE = new javax.swing.JMenuItem();
        FORMANCOVE = new javax.swing.JMenuItem();
        REP_VENT = new javax.swing.JMenu();
        REPCOMPEM1 = new javax.swing.JMenuItem();
        modulo_cp = new javax.swing.JMenu();
        FORMPROVEE = new javax.swing.JMenuItem();
        FORMFORMPA = new javax.swing.JMenuItem();
        FORMCOSAPR = new javax.swing.JMenuItem();
        modulo_cm = new javax.swing.JMenu();
        FORMFACCOM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jcMousePanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lbl_bienvenida.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_bienvenida.setForeground(new java.awt.Color(204, 204, 0));
        lbl_bienvenida.setText("BIENVENIDO..!!");

        lbl_usuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("USUARIO");

        lbl_sucursal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_sucursal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sucursal.setText("SUCURSAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(906, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_bienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_sucursal)
                .addContainerGap())
        );

        jcMousePanel2.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 315));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jcMousePanel2.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/torres_cell.jpg"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jcMousePanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jcMousePanel2);

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        modulo_ajuste.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_ajuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajuste.png"))); // NOI18N
        modulo_ajuste.setText("AJUSTES");
        modulo_ajuste.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_ajuste.setPreferredSize(new java.awt.Dimension(120, 35));

        FORMACCGRU.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMACCGRU.setText("Acceso por grupo");
        modulo_ajuste.add(FORMACCGRU);

        Formusuari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Formusuari.setText("Usuario");
        modulo_ajuste.add(Formusuari);

        FORMSERCOM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMSERCOM.setText("Serie Comprobante");
        modulo_ajuste.add(FORMSERCOM);

        FORMTALONA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMTALONA.setText("Talonario Comprobante");
        modulo_ajuste.add(FORMTALONA);

        FORMTALUSU.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMTALUSU.setText("Talonario por Usuario");
        modulo_ajuste.add(FORMTALUSU);

        FORMBACKUP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMBACKUP.setText("Backup BD");
        modulo_ajuste.add(FORMBACKUP);

        FORMDESCON.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMDESCON.setText("Desconectar");
        modulo_ajuste.add(FORMDESCON);

        FORMSALIR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMSALIR.setText("Salir");
        modulo_ajuste.add(FORMSALIR);

        jMenuBar1.add(modulo_ajuste);

        modulo_ayuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        modulo_ayuda.setText("AYUDA");
        modulo_ayuda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_ayuda.setPreferredSize(new java.awt.Dimension(120, 35));

        FORMCAMPAS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCAMPAS.setText("Cambio Contraseña");
        modulo_ayuda.add(FORMCAMPAS);

        jMenuBar1.add(modulo_ayuda);

        modulo_st.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_st.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        modulo_st.setText("STOCK");
        modulo_st.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_st.setPreferredSize(new java.awt.Dimension(120, 35));

        FORMARTICU.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMARTICU.setText("Articulo");
        FORMARTICU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMARTICUActionPerformed(evt);
            }
        });
        modulo_st.add(FORMARTICU);

        FORMAJUSTK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMAJUSTK.setText("Ajuste de Stock");
        FORMAJUSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMAJUSTKActionPerformed(evt);
            }
        });
        modulo_st.add(FORMAJUSTK);

        FORMCOEXAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCOEXAR.setText("Consulta Exist Articulo");
        FORMCOEXAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCOEXARActionPerformed(evt);
            }
        });
        modulo_st.add(FORMCOEXAR);

        FORMCATART.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCATART.setText("Categoria Articulo");
        FORMCATART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCATARTActionPerformed(evt);
            }
        });
        modulo_st.add(FORMCATART);

        FORMMARART.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMMARART.setText("Marca Articulo");
        FORMMARART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMMARARTActionPerformed(evt);
            }
        });
        modulo_st.add(FORMMARART);

        FORMUNMEAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMUNMEAR.setText("Unidad de medida Articulo");
        FORMUNMEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMUNMEARActionPerformed(evt);
            }
        });
        modulo_st.add(FORMUNMEAR);

        REP_STK.setText("Reportes");
        REP_STK.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N

        REPEXISART.setText("Existencia Articulo");
        REP_STK.add(REPEXISART);

        modulo_st.add(REP_STK);

        jMenuBar1.add(modulo_st);

        modulo_cc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_cc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/client.png"))); // NOI18N
        modulo_cc.setText("GESTION COBROS");
        modulo_cc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_cc.setName(""); // NOI18N
        modulo_cc.setPreferredSize(new java.awt.Dimension(180, 35));

        Formperson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Formperson.setText("Personas");
        Formperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormpersonActionPerformed(evt);
            }
        });
        modulo_cc.add(Formperson);

        FORMCLIENT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCLIENT.setText("Clientes");
        FORMCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCLIENTActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMCLIENT);

        FORMRECIBO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMRECIBO.setText("Recibos De Ventas");
        FORMRECIBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMRECIBOActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMRECIBO);

        FORMHBCJCO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMHBCJCO.setText("Habilitacion Caja");
        FORMHBCJCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMHBCJCOActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMHBCJCO);

        FORMFORMCO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMFORMCO.setText("Forma De Cobro");
        FORMFORMCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMFORMCOActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMFORMCO);

        FORMCIECAJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCIECAJ.setText("Cierre Caja");
        FORMCIECAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCIECAJActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMCIECAJ);

        FORMCOSACL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCOSACL.setText("Consulta Saldo Cliente");
        FORMCOSACL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCOSACLActionPerformed(evt);
            }
        });
        modulo_cc.add(FORMCOSACL);

        REP_COB.setText("Reportes");
        REP_COB.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N

        REPEXTCLI1.setText("Extracto de cuenta cliente");
        REP_COB.add(REPEXTCLI1);

        REPMOVCAJ1.setText("Movimiento de Entrada Caja");
        REP_COB.add(REPMOVCAJ1);

        REPRECEMI1.setText("Recibos Emitidos en fecha");
        REP_COB.add(REPRECEMI1);

        modulo_cc.add(REP_COB);

        jMenuBar1.add(modulo_cc);

        modulo_vt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_vt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sales.png"))); // NOI18N
        modulo_vt.setText("VENTAS Y FACTURACION");
        modulo_vt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_vt.setName(""); // NOI18N
        modulo_vt.setPreferredSize(new java.awt.Dimension(210, 35));

        FORMFACTUR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMFACTUR.setText("Facturacion");
        FORMFACTUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMFACTURActionPerformed(evt);
            }
        });
        modulo_vt.add(FORMFACTUR);

        FORMCONDVE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCONDVE.setText("Condiciones Ventas");
        FORMCONDVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCONDVEActionPerformed(evt);
            }
        });
        modulo_vt.add(FORMCONDVE);

        FORMCNCMVE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCNCMVE.setText("Consulta Comprobantes");
        FORMCNCMVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCNCMVEActionPerformed(evt);
            }
        });
        modulo_vt.add(FORMCNCMVE);

        FORMANCOVE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMANCOVE.setText("Anulacion Comprobante");
        FORMANCOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMANCOVEActionPerformed(evt);
            }
        });
        modulo_vt.add(FORMANCOVE);

        REP_VENT.setText("Reportes");
        REP_VENT.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N

        REPCOMPEM1.setText("Comprobantes Emitidos a la fecha");
        REP_VENT.add(REPCOMPEM1);

        modulo_vt.add(REP_VENT);

        jMenuBar1.add(modulo_vt);

        modulo_cp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_cp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos.png"))); // NOI18N
        modulo_cp.setText("GESTION PAGOS");
        modulo_cp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_cp.setPreferredSize(new java.awt.Dimension(180, 35));

        FORMPROVEE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMPROVEE.setText("Proveedores");
        FORMPROVEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMPROVEEActionPerformed(evt);
            }
        });
        modulo_cp.add(FORMPROVEE);

        FORMFORMPA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMFORMPA.setText("Forma De Pago");
        FORMFORMPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMFORMPAActionPerformed(evt);
            }
        });
        modulo_cp.add(FORMFORMPA);

        FORMCOSAPR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMCOSAPR.setText("Consulta Saldo Proveedor");
        FORMCOSAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMCOSAPRActionPerformed(evt);
            }
        });
        modulo_cp.add(FORMCOSAPR);

        jMenuBar1.add(modulo_cp);

        modulo_cm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        modulo_cm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buy.png"))); // NOI18N
        modulo_cm.setText("COMPRAS");
        modulo_cm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modulo_cm.setName(""); // NOI18N
        modulo_cm.setPreferredSize(new java.awt.Dimension(120, 35));

        FORMFACCOM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FORMFACCOM.setText("Factura Compras");
        FORMFACCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORMFACCOMActionPerformed(evt);
            }
        });
        modulo_cm.add(FORMFACCOM);

        jMenuBar1.add(modulo_cm);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormpersonActionPerformed
        
    }//GEN-LAST:event_FormpersonActionPerformed

    private void FORMARTICUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMARTICUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMARTICUActionPerformed

    private void FORMCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCLIENTActionPerformed

    private void FORMFACTURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMFACTURActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMFACTURActionPerformed

    private void FORMCONDVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCONDVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCONDVEActionPerformed

    private void FORMRECIBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMRECIBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMRECIBOActionPerformed

    private void FORMFORMCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMFORMCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMFORMCOActionPerformed

    private void FORMCOSACLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCOSACLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCOSACLActionPerformed

    private void FORMPROVEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMPROVEEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMPROVEEActionPerformed

    private void FORMFACCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMFACCOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMFACCOMActionPerformed

    private void FORMCOSAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCOSAPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCOSAPRActionPerformed

    private void FORMCOEXARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCOEXARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCOEXARActionPerformed

    private void FORMFORMPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMFORMPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMFORMPAActionPerformed

    private void FORMHBCJCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMHBCJCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMHBCJCOActionPerformed

    private void FORMCIECAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCIECAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCIECAJActionPerformed

    private void FORMCNCMVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCNCMVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCNCMVEActionPerformed

    private void FORMANCOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMANCOVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMANCOVEActionPerformed

    private void FORMCATARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMCATARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMCATARTActionPerformed

    private void FORMMARARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMMARARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMMARARTActionPerformed

    private void FORMUNMEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMUNMEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMUNMEARActionPerformed

    private void REPRECEMI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPRECEMI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REPRECEMI1ActionPerformed

    private void FORMAJUSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMAJUSTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMAJUSTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMMENUPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMMENUPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMMENUPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMMENUPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMMENUPR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem FORMACCGRU;
    public javax.swing.JMenuItem FORMAJUSTK;
    public javax.swing.JMenuItem FORMANCOVE;
    public javax.swing.JMenuItem FORMARTICU;
    public javax.swing.JMenuItem FORMBACKUP;
    public javax.swing.JMenuItem FORMCAMPAS;
    public javax.swing.JMenuItem FORMCATART;
    public javax.swing.JMenuItem FORMCIECAJ;
    public javax.swing.JMenuItem FORMCLIENT;
    public javax.swing.JMenuItem FORMCNCMVE;
    public javax.swing.JMenuItem FORMCOEXAR;
    public javax.swing.JMenuItem FORMCONDVE;
    public javax.swing.JMenuItem FORMCOSACL;
    public javax.swing.JMenuItem FORMCOSAPR;
    public javax.swing.JMenuItem FORMDESCON;
    public javax.swing.JMenuItem FORMFACCOM;
    public javax.swing.JMenuItem FORMFACTUR;
    public javax.swing.JMenuItem FORMFORMCO;
    public javax.swing.JMenuItem FORMFORMPA;
    public javax.swing.JMenuItem FORMHBCJCO;
    public javax.swing.JMenuItem FORMMARART;
    public javax.swing.JMenuItem FORMPROVEE;
    public javax.swing.JMenuItem FORMRECIBO;
    public javax.swing.JMenuItem FORMSALIR;
    public javax.swing.JMenuItem FORMSERCOM;
    public javax.swing.JMenuItem FORMTALONA;
    public javax.swing.JMenuItem FORMTALUSU;
    public javax.swing.JMenuItem FORMUNMEAR;
    public javax.swing.JMenuItem Formperson;
    public javax.swing.JMenuItem Formusuari;
    public javax.swing.JMenuItem REPCOMPEM1;
    public javax.swing.JMenuItem REPEXISART;
    public javax.swing.JMenuItem REPEXTCLI1;
    public javax.swing.JMenuItem REPMOVCAJ1;
    public javax.swing.JMenuItem REPRECEMI1;
    public javax.swing.JMenu REP_COB;
    public javax.swing.JMenu REP_STK;
    public javax.swing.JMenu REP_VENT;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    public javax.swing.JLabel lbl_bienvenida;
    public javax.swing.JLabel lbl_sucursal;
    public javax.swing.JLabel lbl_usuario;
    public javax.swing.JMenu modulo_ajuste;
    public javax.swing.JMenu modulo_ayuda;
    public javax.swing.JMenu modulo_cc;
    public javax.swing.JMenu modulo_cm;
    public javax.swing.JMenu modulo_cp;
    public javax.swing.JMenu modulo_st;
    public javax.swing.JMenu modulo_vt;
    // End of variables declaration//GEN-END:variables

    

}
