
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;


public class FORMARTICU extends javax.swing.JFrame {

    /**
     * Creates new form FORMARTICU
     */
    public FORMARTICU() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_articulo();
    }
private void cerrar_ventan_articulo() {
        setDefaultCloseOperation(FORMARTICU.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanaarticulo();
            }
        });
    }
   public void cerrar_ventanaarticulo(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_proveedor = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_prov = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_bdesc_prov = new javax.swing.JTextField();
        txt_bnro_prov = new javax.swing.JTextField();
        btn_agregar_prov = new javax.swing.JButton();
        ventana_marca = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_bmarca = new javax.swing.JTable();
        btn_agregar_marca = new javax.swing.JButton();
        txt_bdesc_marca = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ventana_categoria = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txt_bdesc_categoria = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_bcategoria = new javax.swing.JTable();
        btn_agregar_categ = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ventana_iva = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_biva = new javax.swing.JTable();
        btn_agregar_iva = new javax.swing.JButton();
        ventana_deposito = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_bdeposito = new javax.swing.JTable();
        btn_agreg_dep = new javax.swing.JButton();
        ventana_sucursal = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        tbl_bsucursal = new javax.swing.JTable();
        btn_agreg_suc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ventana_error = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_error = new javax.swing.JTextArea();
        btn_volver_err = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_cod_articulo = new javax.swing.JTextField();
        txt_desc_art = new javax.swing.JTextField();
        txt_cod_prov = new javax.swing.JTextField();
        txt_desc_prov = new javax.swing.JTextField();
        txt_cod_marca = new javax.swing.JTextField();
        txt_desc_marca = new javax.swing.JTextField();
        txt_cod_categ = new javax.swing.JTextField();
        txt_desc_categ = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_cod_iva = new javax.swing.JTextField();
        txt_desc_iva = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        cmb_man_stock = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_cod = new javax.swing.JLabel();
        campo_obligatorio = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        lbl_prov = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        lbl_iva = new javax.swing.JLabel();
        cmb_un_med = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_nro_lote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_busq_prov = new javax.swing.JButton();
        btn_busq_marca = new javax.swing.JButton();
        btn_busq_categ = new javax.swing.JButton();
        lbl_cod_un_med = new javax.swing.JLabel();
        lbl_nro_lote = new javax.swing.JLabel();
        txt_precio_compra = new javax.swing.JTextField();
        txt_precio_vent = new javax.swing.JTextField();
        btn_busq_iva = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_articulo = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_error = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        ventana_proveedor.setTitle("BUSQUEDA PROVEEDORES");
        ventana_proveedor.setResizable(false);
        ventana_proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_prov = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_prov);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, 250));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Nro Doc/R.U.C");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("NOMBRE");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));
        jPanel12.add(txt_bdesc_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, -1));
        jPanel12.add(txt_bnro_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        btn_agregar_prov.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_prov.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar_prov.setText("Agregar");
        jPanel12.add(btn_agregar_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, 25));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 350));

        ventana_proveedor.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        ventana_marca.setTitle("BUSQUEDA MARCA");
        ventana_marca.setResizable(false);
        ventana_marca.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bmarca = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bmarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_bmarca);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 230));

        btn_agregar_marca.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_marca.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btn_agregar_marca.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar_marca.setText("Agregar");
        jPanel13.add(btn_agregar_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, 25));

        txt_bdesc_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bdesc_marcaActionPerformed(evt);
            }
        });
        jPanel13.add(txt_bdesc_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, -1));

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Descripcion");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 330));

        ventana_marca.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 350));

        ventana_categoria.setTitle("BUSQUEDA CATEGORIA");
        ventana_categoria.setResizable(false);
        ventana_categoria.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(txt_bdesc_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, -1));

        tbl_bcategoria = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_bcategoria);

        jPanel14.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 230));

        btn_agregar_categ.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_categ.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btn_agregar_categ.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar_categ.setText("Agregar");
        btn_agregar_categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_categActionPerformed(evt);
            }
        });
        jPanel14.add(btn_agregar_categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, 25));

        jLabel17.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("Descripcion");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 330));

        ventana_categoria.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 360));

        ventana_iva.setTitle("BUSQUEDA I.V.A");
        ventana_iva.setResizable(false);
        ventana_iva.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_biva = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_biva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_biva);

        jPanel15.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 180));

        btn_agregar_iva.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_iva.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btn_agregar_iva.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar_iva.setText("Agregar");
        jPanel15.add(btn_agregar_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 25));

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 230));

        ventana_iva.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 250));

        ventana_deposito.setTitle("DEPOSITOS");
        ventana_deposito.setResizable(false);
        ventana_deposito.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bsucursal = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bdeposito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbl_bdeposito);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 170));

        btn_agreg_dep.setText("Agregar");
        btn_agreg_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_depActionPerformed(evt);
            }
        });
        jPanel4.add(btn_agreg_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        ventana_deposito.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        ventana_sucursal.setTitle("Busqueda Sucursales");
        ventana_sucursal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bsucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPanel5.add(tbl_bsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 370, 150));

        btn_agreg_suc.setText("Agregar");
        btn_agreg_suc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreg_sucActionPerformed(evt);
            }
        });
        jPanel5.add(btn_agreg_suc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        ventana_sucursal.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        ventana_error.setTitle("VENTANA DE ERROR DEL SISTEMA");
        ventana_error.setResizable(false);
        ventana_error.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_error.setEditable(false);
        txt_error.setColumns(20);
        txt_error.setLineWrap(true);
        txt_error.setRows(5);
        txt_error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setViewportView(txt_error);

        jPanel11.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 250));

        btn_volver_err.setBackground(new java.awt.Color(255, 102, 0));
        btn_volver_err.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btn_volver_err.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver_err.setText("Volver");
        jPanel11.add(btn_volver_err, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 310));

        ventana_error.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        setTitle("REGISTRO ARTICULOS(FORMARTICU)");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cod_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_articuloActionPerformed(evt);
            }
        });
        txt_cod_articulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_articuloKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, 150, 20));

        txt_desc_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_artActionPerformed(evt);
            }
        });
        txt_desc_art.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_desc_artKeyTyped(evt);
            }
        });
        jPanel1.add(txt_desc_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 110, 330, 20));

        txt_cod_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_provKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, 20));
        jPanel1.add(txt_desc_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 140, 210, 20));

        txt_cod_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_marcaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 50, 20));
        jPanel1.add(txt_desc_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 170, 210, 20));

        txt_cod_categ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_categKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 20));
        jPanel1.add(txt_desc_categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 200, 210, 20));

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 50, 20));

        txt_cod_iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_ivaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 50, 20));

        txt_desc_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_ivaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_desc_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 70, 20));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 150, 20));

        cmb_man_stock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmb_man_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 150, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nro Lote:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Proveedor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Categoria:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Precio compra:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio venta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("I.V.A:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Estado:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Maneja stock:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        lbl_cod.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod.setForeground(new java.awt.Color(255, 51, 102));
        lbl_cod.setText("*");
        jPanel1.add(lbl_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, -1, -1));

        campo_obligatorio.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        campo_obligatorio.setForeground(new java.awt.Color(255, 51, 51));
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS *");
        jPanel1.add(campo_obligatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        lbl_desc.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_desc.setForeground(new java.awt.Color(255, 51, 102));
        lbl_desc.setText("*");
        jPanel1.add(lbl_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        lbl_prov.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_prov.setForeground(new java.awt.Color(255, 51, 102));
        lbl_prov.setText("*");
        jPanel1.add(lbl_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        lbl_estado.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_estado.setForeground(new java.awt.Color(255, 51, 102));
        lbl_estado.setText("*");
        jPanel1.add(lbl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, -1, -1));

        lbl_iva.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_iva.setForeground(new java.awt.Color(255, 51, 102));
        lbl_iva.setText("*");
        jPanel1.add(lbl_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        cmb_un_med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmb_un_med, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 50, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txt_nro_lote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nro_loteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nro_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 80, 150, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Unidad Med:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btn_busq_prov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_prov.setToolTipText("Buscar");
        jPanel1.add(btn_busq_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 140, 25, 20));

        btn_busq_marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_marca.setToolTipText("Buscar");
        jPanel1.add(btn_busq_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 170, 25, 20));

        btn_busq_categ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_categ.setToolTipText("Buscar");
        jPanel1.add(btn_busq_categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 200, 25, 20));

        lbl_cod_un_med.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_cod_un_med.setForeground(new java.awt.Color(255, 51, 102));
        lbl_cod_un_med.setText("*");
        jPanel1.add(lbl_cod_un_med, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 50, -1, -1));

        lbl_nro_lote.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_nro_lote.setForeground(new java.awt.Color(255, 51, 102));
        lbl_nro_lote.setText("*");
        jPanel1.add(lbl_nro_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 80, -1, -1));

        txt_precio_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precio_compraKeyTyped(evt);
            }
        });
        jPanel1.add(txt_precio_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 150, 20));

        txt_precio_vent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precio_ventKeyTyped(evt);
            }
        });
        jPanel1.add(txt_precio_vent, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 150, 20));

        btn_busq_iva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_iva.setToolTipText("Buscar");
        jPanel1.add(btn_busq_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 110, 25, 20));

        jLabel18.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setText("Busq(F9)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setText("Busq(F9)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setText("Busq(F9)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setText("Busq(F9)");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 850, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_articulo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_articulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_articuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_articulo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 280));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 850, 300));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setBackground(new java.awt.Color(0, 51, 255));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyPressed(evt);
            }
        });
        jPanel16.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 80, 25));

        btn_guardar.setBackground(new java.awt.Color(0, 51, 255));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Confirmar");
        btn_guardar.setToolTipText("GRABAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        btn_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_guardarKeyPressed(evt);
            }
        });
        jPanel16.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 105, 25));

        btn_actualizar.setBackground(new java.awt.Color(0, 51, 255));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Editar");
        btn_actualizar.setToolTipText("Modificar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel16.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 25));

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel16.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 95, 25));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel16.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 10, 100, 25));

        btn_busqueda.setBackground(new java.awt.Color(0, 153, 0));
        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        btn_busqueda.setText("Buscar");
        btn_busqueda.setToolTipText("Buscar");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });
        jPanel16.add(btn_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 85, 25));

        btn_ejecutar.setBackground(new java.awt.Color(0, 153, 0));
        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.setToolTipText("Ejecutar");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jPanel16.add(btn_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 95, 25));

        btn_error.setBackground(new java.awt.Color(255, 102, 0));
        btn_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_error.setForeground(new java.awt.Color(255, 255, 255));
        btn_error.setText("Ver Error");
        btn_error.setToolTipText("Ver Error");
        btn_error.setFocusable(false);
        btn_error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_error.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_errorActionPerformed(evt);
            }
        });
        jPanel16.add(btn_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 10, 100, 25));

        btn_salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel16.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 10, 70, 25));

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 850, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_desc_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_artActionPerformed

    private void txt_desc_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_ivaActionPerformed

    private void txt_cod_articuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_articuloKeyTyped
        int num=20;
        if(txt_cod_articulo.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_articuloKeyTyped

    private void txt_desc_artKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_desc_artKeyTyped
         int num=80;
        if(txt_desc_art.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_desc_artKeyTyped

    private void txt_cod_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_provKeyTyped
        int num=3;
        if(txt_cod_prov.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_provKeyTyped

    private void txt_cod_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_marcaKeyTyped
        int num=5;
        if(txt_cod_marca.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_marcaKeyTyped

    private void txt_cod_categKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_categKeyTyped
        int num=5;
        if(txt_cod_categ.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_categKeyTyped

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        txt_cod_iva.requestFocus();
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void tbl_articuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_articuloMouseClicked
        
    }//GEN-LAST:event_tbl_articuloMouseClicked

    private void txt_cod_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_articuloActionPerformed

    private void btn_agreg_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_depActionPerformed

    private void btn_agreg_sucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreg_sucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agreg_sucActionPerformed

    private void txt_bdesc_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bdesc_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bdesc_marcaActionPerformed

    private void btn_agregar_categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_categActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar_categActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_errorActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_guardarKeyPressed

    }//GEN-LAST:event_btn_guardarKeyPressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyPressed

    }//GEN-LAST:event_btn_nuevoKeyPressed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_nro_loteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_loteKeyTyped
        char tecla;
        int num=20;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_nro_lote.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nro_loteKeyTyped

    private void txt_precio_compraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precio_compraKeyTyped
        char tecla;
        int num = 15;
        tecla = evt.getKeyChar();
        //Validacion de solo numero o decimales
        if(((tecla < '0') || (tecla > '9')) && (tecla != KeyEvent.VK_BACK_SPACE) && (tecla !='.')){
            evt.consume();
            getToolkit().beep();
        }
        if (txt_precio_compra.getText().length() >= num) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_precio_compraKeyTyped

    private void txt_precio_ventKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precio_ventKeyTyped
        char tecla;
        int num = 15;
        tecla = evt.getKeyChar();
        //Validacion de solo numero o decimales
        if(((tecla < '0') || (tecla > '9')) && (tecla != KeyEvent.VK_BACK_SPACE) && (tecla !='.')){
            evt.consume();
            getToolkit().beep();
        }
        if (txt_precio_vent.getText().length() >= num) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_precio_ventKeyTyped

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        char tecla;
        int num = 5;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cantidad.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void txt_cod_ivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_ivaKeyTyped
        char tecla;
        int num = 2;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_iva.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_ivaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMARTICU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMARTICU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMARTICU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMARTICU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMARTICU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_agreg_dep;
    public javax.swing.JButton btn_agreg_suc;
    public javax.swing.JButton btn_agregar_categ;
    public javax.swing.JButton btn_agregar_iva;
    public javax.swing.JButton btn_agregar_marca;
    public javax.swing.JButton btn_agregar_prov;
    public javax.swing.JButton btn_busq_categ;
    public javax.swing.JButton btn_busq_iva;
    public javax.swing.JButton btn_busq_marca;
    public javax.swing.JButton btn_busq_prov;
    public javax.swing.JButton btn_busqueda;
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_error;
    public javax.swing.JButton btn_guardar;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_volver_err;
    public javax.swing.JLabel campo_obligatorio;
    public javax.swing.JComboBox<String> cmb_estado;
    public javax.swing.JComboBox<String> cmb_man_stock;
    public javax.swing.JComboBox<String> cmb_un_med;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JLabel lbl_cod;
    public javax.swing.JLabel lbl_cod_un_med;
    public javax.swing.JLabel lbl_desc;
    public javax.swing.JLabel lbl_estado;
    public javax.swing.JLabel lbl_iva;
    public javax.swing.JLabel lbl_nro_lote;
    public javax.swing.JLabel lbl_prov;
    public javax.swing.JTable tbl_articulo;
    public javax.swing.JTable tbl_bcategoria;
    public javax.swing.JTable tbl_bdeposito;
    public javax.swing.JTable tbl_biva;
    public javax.swing.JTable tbl_bmarca;
    public javax.swing.JTable tbl_bsucursal;
    public javax.swing.JTable tbl_prov;
    public javax.swing.JTextField txt_bdesc_categoria;
    public javax.swing.JTextField txt_bdesc_marca;
    public javax.swing.JTextField txt_bdesc_prov;
    public javax.swing.JTextField txt_bnro_prov;
    public javax.swing.JTextField txt_cantidad;
    public javax.swing.JTextField txt_cod_articulo;
    public javax.swing.JTextField txt_cod_categ;
    public javax.swing.JTextField txt_cod_iva;
    public javax.swing.JTextField txt_cod_marca;
    public javax.swing.JTextField txt_cod_prov;
    public javax.swing.JTextField txt_desc_art;
    public javax.swing.JTextField txt_desc_categ;
    public javax.swing.JTextField txt_desc_iva;
    public javax.swing.JTextField txt_desc_marca;
    public javax.swing.JTextField txt_desc_prov;
    public javax.swing.JTextArea txt_error;
    public javax.swing.JTextField txt_nro_lote;
    public javax.swing.JTextField txt_precio_compra;
    public javax.swing.JTextField txt_precio_vent;
    private javax.swing.JDialog ventana_categoria;
    private javax.swing.JDialog ventana_deposito;
    private javax.swing.JDialog ventana_error;
    private javax.swing.JDialog ventana_iva;
    private javax.swing.JDialog ventana_marca;
    private javax.swing.JDialog ventana_proveedor;
    private javax.swing.JDialog ventana_sucursal;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_combobox();
        ocultar_label();
    }

    private void bloquea_campos() {
        txt_cantidad.setEditable(false);
        txt_cod_articulo.setEditable(false);
        txt_cod_categ.setEditable(false);
        txt_cod_iva.setEditable(false);
        txt_cod_marca.setEditable(false);
        txt_cod_prov.setEditable(false);
        txt_desc_art.setEditable(false);
        txt_desc_categ.setEditable(false);
        txt_desc_iva.setEditable(false);
        txt_desc_marca.setEditable(false);
        txt_desc_prov.setEditable(false);
        txt_precio_compra.setEditable(false);
        txt_precio_vent.setEditable(false);
        txt_nro_lote.setEditable(false);
        btn_busq_categ.setEnabled(false);
        btn_busq_iva.setEnabled(false);
        btn_busq_marca.setEnabled(false);
        btn_busq_prov.setEnabled(false);
        cmb_un_med.setEnabled(false);
        cmb_estado.setEnabled(false);
        cmb_man_stock.setEnabled(false);
    }

    private void bloquea_botones() {
        btn_actualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_ejecutar.setEnabled(false);
        btn_error.setEnabled(false);
        btn_busqueda.setEnabled(true);
        btn_nuevo.setEnabled(true);
        btn_nuevo.requestFocus();
    }

    public void carga_combobox() {
        //CARGA ESTADO
        Object tpd[] = new Object[2];
        tpd[0] = "ACTIVO";
        tpd[1] = "INACTIVO";
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(tpd);
        this.cmb_estado.setModel(dcb);
        String std = "ACTIVO";
        this.cmb_estado.setSelectedItem(std);
        //CARGA INDICADOR DE CONTROL DE STOCK
        Object tpu[] = new Object[2];
        tpu[0] = "SI";
        tpu[1] = "NO";
        DefaultComboBoxModel dcu = new DefaultComboBoxModel(tpu);
        this.cmb_man_stock.setModel(dcu);
        String upd = "SI";
        this.cmb_man_stock.setSelectedItem(upd);
        
    }

    public void habilita_campos() {
        txt_cantidad.setEditable(true);
        txt_cod_articulo.setEditable(true);
        txt_cod_categ.setEditable(true);
        txt_cod_iva.setEditable(true);
        txt_cod_marca.setEditable(true);
        txt_cod_prov.setEditable(true);
        txt_desc_art.setEditable(true);
        txt_precio_compra.setEditable(true);
        txt_precio_vent.setEditable(true);
        txt_nro_lote.setEditable(true);
        
        btn_busq_categ.setEnabled(true);
        btn_busq_iva.setEnabled(true);
        btn_busq_marca.setEnabled(true);
        btn_busq_prov.setEnabled(true);
        
        cmb_un_med.setEnabled(true);
        cmb_estado.setEnabled(true);
        cmb_man_stock.setEnabled(true);
        txt_cod_articulo.requestFocus();
    }
    public void limpia_campos() {
        txt_cantidad.setText("");
        txt_cod_articulo.setText("");
        txt_nro_lote.setText("");
        txt_cod_categ.setText("");
        txt_cod_iva.setText("");
        txt_cod_marca.setText("");
        txt_cod_prov.setText("");
        txt_desc_art.setText("");
        txt_desc_categ.setText("");
        txt_desc_iva.setText("");
        txt_desc_marca.setText("");
        txt_desc_prov.setText("");
        txt_precio_compra.setText("");
        txt_precio_vent.setText("");
    }
    public void ventana_deposito(){
    FORMARTICU bus = new FORMARTICU();
        ventana_deposito.setVisible(true);
        ventana_deposito.setSize(400,250);
        ventana_deposito.setLocationRelativeTo(bus);
    }
    public void ventana_sucursal(){
    FORMARTICU bus = new FORMARTICU();
        ventana_sucursal.setVisible(true);
        ventana_sucursal.setSize(400,250);
        ventana_sucursal.setLocationRelativeTo(bus);
    }
    public void ventana_proveedor(){
    FORMARTICU bus = new FORMARTICU();
        ventana_proveedor.setVisible(true);
        ventana_proveedor.setSize(420,395);
        ventana_proveedor.setLocationRelativeTo(bus);
        txt_bnro_prov.setText("");
        txt_bdesc_prov.setText("%");
        txt_bnro_prov.requestFocus();
}
    public void ventana_marca(){
        FORMARTICU bus = new FORMARTICU();
        ventana_marca.setVisible(true);
        ventana_marca.setSize(380,375);
        txt_bdesc_marca.setText("%%");
        ventana_marca.setLocationRelativeTo(bus);
}
    public void ventana_categoria(){
    FORMARTICU bus = new FORMARTICU();
        ventana_categoria.setVisible(true);
        ventana_categoria.setSize(380,375);
        txt_bdesc_categoria.setText("%%");
        ventana_categoria.setLocationRelativeTo(bus);
}
    public void ventana_iva(){
    FORMARTICU bus = new FORMARTICU();
        ventana_iva.setVisible(true);
        ventana_iva.setSize(300,270);
        ventana_iva.setLocationRelativeTo(bus);
}

public void cerrar_ventana_deposito(){
        ventana_deposito.dispose();
}
public void cerrar_ventana_sucursal(){
        ventana_sucursal.dispose();
}
public void cerrar_ventana_proveedor(){
        ventana_proveedor.dispose();
}
public void cerrar_ventana_marca(){
        ventana_marca.dispose();
}
public void cerrar_ventana_categoria(){
        ventana_categoria.dispose();
}
public void cerrar_ventana_iva(){
        ventana_iva.dispose();
}
public void ventana_error(){
    FORMARTICU bus = new FORMARTICU();
        ventana_error.setVisible(true);
        ventana_error.setSize(590,355);
        ventana_error.setLocationRelativeTo(bus);
    }
    public void cerrar_ventana_error(){
        ventana_error.dispose();
}
public void ocultar_label() {
    lbl_cod.setVisible(false);
    lbl_desc.setVisible(false);
    lbl_estado.setVisible(false);
    lbl_prov.setVisible(false);
    lbl_iva.setVisible(false);
    lbl_cod_un_med.setVisible(false);
    lbl_nro_lote.setVisible(false);
    campo_obligatorio.setVisible(false);
}
}
