
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JONY
 */
public class FORMCLIENT extends javax.swing.JFrame {

    public FORMCLIENT() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_cliente();
    }
private void cerrar_ventan_cliente() {
        setDefaultCloseOperation(FORMCLIENT.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanacliente();
            }
        });
    }
   public void cerrar_ventanacliente(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_persona = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bpersona = new javax.swing.JTable();
        txt_bnombre_persona = new javax.swing.JTextField();
        txt_bnrodoc_persona = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        ventana_moneda = new javax.swing.JDialog();
        jPanel17 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bmoneda = new javax.swing.JTable();
        btn_agregar_moneda = new javax.swing.JButton();
        ventana_cobrador = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_bcobrador = new javax.swing.JTable();
        txt_bnombre_cobrador = new javax.swing.JTextField();
        btn_agregar_cobrador = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ventana_vendedor = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_bvendedor = new javax.swing.JTable();
        txt_bnombre_vendedor = new javax.swing.JTextField();
        btn_agregar_vendedor = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ventana_condicion = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_bcondicion = new javax.swing.JTable();
        txt_bcondicion = new javax.swing.JTextField();
        btn_agregar_cond_venta = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ventana_tipo_cliente = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_btipo_cliente = new javax.swing.JTable();
        btn_agregar_tip_cliente = new javax.swing.JButton();
        ventana_error = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_error = new javax.swing.JTextArea();
        btn_volver_err = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cod_cliente = new javax.swing.JTextField();
        txt_cod_persona = new javax.swing.JTextField();
        txt_desc_persona = new javax.swing.JTextField();
        txt_cod_moneda = new javax.swing.JTextField();
        txt_desc_moneda = new javax.swing.JTextField();
        txt_cod_cobrador = new javax.swing.JTextField();
        txt_desc_cobrador = new javax.swing.JTextField();
        txt_cod_vendedor = new javax.swing.JTextField();
        txt_desc_vendedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cod_condicion = new javax.swing.JTextField();
        txt_desc_condicion = new javax.swing.JTextField();
        txt_cod_tipo_cliente = new javax.swing.JTextField();
        txt_desc_tipo_cliente = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        txt_comentario = new javax.swing.JTextField();
        lblcod = new javax.swing.JLabel();
        lblmoneda = new javax.swing.JLabel();
        lblcobrador = new javax.swing.JLabel();
        lblvendedor = new javax.swing.JLabel();
        lblcondicion = new javax.swing.JLabel();
        lbltipocliente = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        campo_obligatorio = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        btn_persona = new javax.swing.JButton();
        btn_busq_cod_tip_cli = new javax.swing.JButton();
        btn_busq_cod_pers = new javax.swing.JButton();
        btn_busq_cod_mone = new javax.swing.JButton();
        btn_busq_cod_cob = new javax.swing.JButton();
        btn_busq_cod_ven = new javax.swing.JButton();
        btn_busq_cod_cond = new javax.swing.JButton();
        txt_lim_credito = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cliente = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_error = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        ventana_persona.setTitle("BUSQUEDA PERSONAS");
        ventana_persona.setResizable(false);
        ventana_persona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bpersona = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_bpersona);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 420, 260));
        jPanel4.add(txt_bnombre_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 230, 20));

        txt_bnrodoc_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bnrodoc_personaActionPerformed(evt);
            }
        });
        jPanel4.add(txt_bnrodoc_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("NUMERO DOCUMENTO");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("NOMBRE");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        btn_agregar.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar.setText("AGREGAR");
        jPanel4.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 335, -1, -1));

        jPanel10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 369));

        ventana_persona.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        ventana_moneda.setTitle("BUSQUEDA MONEDAS");
        ventana_moneda.setResizable(false);
        ventana_moneda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(153, 153, 153));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bmoneda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bmoneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_bmoneda);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 260, 120));

        btn_agregar_moneda.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_moneda.setText("AGREGAR");
        jPanel5.add(btn_agregar_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 25));

        jPanel17.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 170));

        ventana_moneda.getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 190));

        ventana_cobrador.setTitle("BUSQUEDA COBRADORES");
        ventana_cobrador.setResizable(false);
        ventana_cobrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bcobrador = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcobrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_bcobrador);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 350, 230));
        jPanel6.add(txt_bnombre_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 11, 150, -1));

        btn_agregar_cobrador.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_cobrador.setText("AGREGAR");
        jPanel6.add(btn_agregar_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 306, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("NOMBRE");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jPanel11.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 340));

        ventana_cobrador.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        ventana_vendedor.setTitle("BUSQUEDA VENDEDORES");
        ventana_vendedor.setResizable(false);
        ventana_vendedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bvendedor = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bvendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_bvendedor);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 240));
        jPanel7.add(txt_bnombre_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 11, 150, -1));

        btn_agregar_vendedor.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_vendedor.setText("AGREGAR");
        jPanel7.add(btn_agregar_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("NOMBRE");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jPanel12.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 340));

        ventana_vendedor.getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        ventana_condicion.setTitle("BUSQUEDA CONDICIONES DE VENTAS");
        ventana_condicion.setResizable(false);
        ventana_condicion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bcondicion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_bcondicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_bcondicion);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 350, 240));
        jPanel8.add(txt_bcondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, 25));

        btn_agregar_cond_venta.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_cond_venta.setText("AGREGAR");
        btn_agregar_cond_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_cond_ventaActionPerformed(evt);
            }
        });
        jPanel8.add(btn_agregar_cond_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Descripcion");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel13.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 340));

        ventana_condicion.getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        ventana_tipo_cliente.setTitle("BUSQUEDA TIPO CLIENTE");
        ventana_tipo_cliente.setResizable(false);
        ventana_tipo_cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_btipo_cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_btipo_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbl_btipo_cliente);

        jPanel9.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 360, 280));

        btn_agregar_tip_cliente.setBackground(new java.awt.Color(255, 102, 0));
        btn_agregar_tip_cliente.setText("Agregar");
        jPanel9.add(btn_agregar_tip_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jPanel14.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 330));

        ventana_tipo_cliente.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        ventana_error.setTitle("VENTANA DE ERROR DEL SISTEMA");
        ventana_error.setResizable(false);
        ventana_error.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_error.setEditable(false);
        txt_error.setColumns(20);
        txt_error.setLineWrap(true);
        txt_error.setRows(5);
        txt_error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setViewportView(txt_error);

        jPanel16.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 250));

        btn_volver_err.setBackground(new java.awt.Color(255, 102, 0));
        btn_volver_err.setText("Volver");
        jPanel16.add(btn_volver_err, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 310));

        ventana_error.getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO CLIENTES(FORMCLIENT)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setText("Codigo Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setText("Codigo Persona:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setText("Codigo Moneda:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 106, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setText("Codigo Cobrador:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 106, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setText("Codigo Vendedor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txt_cod_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_clienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 50, 20));

        txt_cod_persona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_personaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 55, 50, 20));
        jPanel1.add(txt_desc_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 55, 250, 20));

        txt_cod_moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_monedaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 95, 50, 20));
        jPanel1.add(txt_desc_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 95, 250, 20));

        txt_cod_cobrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_cobradorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 135, 50, 20));
        jPanel1.add(txt_desc_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 135, 250, 20));

        txt_cod_vendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_vendedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 175, 50, 20));
        jPanel1.add(txt_desc_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 175, 250, 20));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel6.setText("Limite De Credito:");
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setText("Condicion De Venta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel8.setText("Tipo De Cliente:");
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setText("Estado:");
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel10.setText("Comentario:");
        jLabel10.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 180, -1, -1));

        txt_cod_condicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_condicionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 215, 50, 20));
        jPanel1.add(txt_desc_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 215, 250, 20));

        txt_cod_tipo_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_tipo_clienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cod_tipo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 55, 50, 20));
        jPanel1.add(txt_desc_tipo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 55, 170, 20));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 135, 200, 20));

        txt_comentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_comentarioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 175, 250, 20));

        lblcod.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblcod.setForeground(new java.awt.Color(255, 51, 51));
        lblcod.setText("*");
        jPanel1.add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 15, -1, -1));

        lblmoneda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblmoneda.setForeground(new java.awt.Color(255, 51, 51));
        lblmoneda.setText("*");
        jPanel1.add(lblmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        lblcobrador.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblcobrador.setForeground(new java.awt.Color(255, 51, 51));
        lblcobrador.setText("*");
        jPanel1.add(lblcobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, -1, -1));

        lblvendedor.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblvendedor.setForeground(new java.awt.Color(255, 51, 51));
        lblvendedor.setText("*");
        jPanel1.add(lblvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        lblcondicion.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblcondicion.setForeground(java.awt.Color.orange);
        lblcondicion.setText("*");
        jPanel1.add(lblcondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 16, -1, -1));

        lbltipocliente.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbltipocliente.setForeground(java.awt.Color.orange);
        lbltipocliente.setText("*");
        jPanel1.add(lbltipocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 64, -1, -1));

        lblestado.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblestado.setForeground(java.awt.Color.orange);
        lblestado.setText("*");
        jPanel1.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        campo_obligatorio.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        campo_obligatorio.setForeground(new java.awt.Color(255, 51, 51));
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS *");
        jPanel1.add(campo_obligatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 220, -1, -1));

        lblcodigo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblcodigo.setForeground(java.awt.Color.orange);
        lblcodigo.setText("*");
        jPanel1.add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 16, -1, -1));

        lblnom.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblnom.setForeground(new java.awt.Color(255, 51, 51));
        lblnom.setText("*");
        jPanel1.add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        btn_persona.setText("Persona");
        jPanel1.add(btn_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 55, 105, 25));

        btn_busq_cod_tip_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_tip_cli.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_tip_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 55, 25, 20));

        btn_busq_cod_pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_pers.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 55, 25, 20));

        btn_busq_cod_mone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_mone.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_mone, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 95, 25, 20));

        btn_busq_cod_cob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_cob.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_cob, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 135, 25, 20));

        btn_busq_cod_ven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_ven.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_ven, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 175, 25, 20));

        btn_busq_cod_cond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_busq_cod_cond.setToolTipText("Buscar");
        jPanel1.add(btn_busq_cod_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 215, 25, 20));
        jPanel1.add(txt_lim_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 95, 200, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 260));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 250));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1000, 270));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setBackground(new java.awt.Color(0, 51, 255));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyPressed(evt);
            }
        });
        jPanel18.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 25));

        btn_guardar.setBackground(new java.awt.Color(0, 51, 255));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Confirmar");
        btn_guardar.setToolTipText("GRABAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        btn_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_guardarKeyPressed(evt);
            }
        });
        jPanel18.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 10, 105, 25));

        btn_actualizar.setBackground(new java.awt.Color(0, 51, 255));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Editar");
        btn_actualizar.setToolTipText("Modificar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel18.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 10, 80, 25));

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel18.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 95, 25));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel18.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 10, 100, 25));

        btn_busqueda.setBackground(new java.awt.Color(0, 153, 0));
        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        btn_busqueda.setText("Buscar");
        btn_busqueda.setToolTipText("Buscar");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });
        jPanel18.add(btn_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 85, 25));

        btn_ejecutar.setBackground(new java.awt.Color(0, 153, 0));
        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.setToolTipText("Ejecutar");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jPanel18.add(btn_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 95, 25));

        btn_error.setBackground(new java.awt.Color(255, 102, 0));
        btn_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_error.setForeground(new java.awt.Color(255, 255, 255));
        btn_error.setText("Ver Error");
        btn_error.setToolTipText("Ver Error");
        btn_error.setFocusable(false);
        btn_error.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_error.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_errorActionPerformed(evt);
            }
        });
        jPanel18.add(btn_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 25));

        btn_salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel18.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 70, 25));

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 990, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cod_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_clienteKeyTyped
        char tecla;
        int num=15;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_cliente.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_clienteKeyTyped

    private void txt_cod_personaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_personaKeyTyped
        char tecla;
        int num=15;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_persona.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_personaKeyTyped

    private void txt_comentarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comentarioKeyTyped
        int num=100;
        if(txt_comentario.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_comentarioKeyTyped

    private void txt_cod_condicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_condicionKeyTyped
        char tecla;
        int num=3;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_condicion.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_condicionKeyTyped

    private void txt_cod_monedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_monedaKeyTyped
        int num=5;
        if(txt_cod_moneda.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_monedaKeyTyped

    private void txt_cod_cobradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_cobradorKeyTyped
       int num=5;
        if(txt_cod_cobrador.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_cobradorKeyTyped

    private void txt_cod_vendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_vendedorKeyTyped
        int num=5;
        if(txt_cod_moneda.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_vendedorKeyTyped

    private void txt_cod_tipo_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_tipo_clienteKeyTyped
        int num=5;
        if(txt_cod_tipo_cliente.getText().length()>=num){
            evt.consume();
        }
        char charecter = evt.getKeyChar();
            if (Character.isLowerCase(charecter)) {
		evt.setKeyChar(Character.toUpperCase(charecter));
		}
    }//GEN-LAST:event_txt_cod_tipo_clienteKeyTyped

    private void tbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clienteMouseClicked
        //btneliminar.setEnabled(true);
    }//GEN-LAST:event_tbl_clienteMouseClicked

    private void txt_bnrodoc_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bnrodoc_personaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bnrodoc_personaActionPerformed

    private void btn_agregar_cond_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_cond_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar_cond_ventaActionPerformed

    private void cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estadoActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyPressed

    }//GEN-LAST:event_btn_nuevoKeyPressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_guardarKeyPressed

    }//GEN-LAST:event_btn_guardarKeyPressed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed

    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_errorActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMCLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMCLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMCLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMCLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMCLIENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_agregar;
    public javax.swing.JButton btn_agregar_cobrador;
    public javax.swing.JButton btn_agregar_cond_venta;
    public javax.swing.JButton btn_agregar_moneda;
    public javax.swing.JButton btn_agregar_tip_cliente;
    public javax.swing.JButton btn_agregar_vendedor;
    public javax.swing.JButton btn_busq_cod_cob;
    public javax.swing.JButton btn_busq_cod_cond;
    public javax.swing.JButton btn_busq_cod_mone;
    public javax.swing.JButton btn_busq_cod_pers;
    public javax.swing.JButton btn_busq_cod_tip_cli;
    public javax.swing.JButton btn_busq_cod_ven;
    public javax.swing.JButton btn_busqueda;
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_error;
    public javax.swing.JButton btn_guardar;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_persona;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_volver_err;
    public javax.swing.JLabel campo_obligatorio;
    public javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JLabel lblcobrador;
    public javax.swing.JLabel lblcod;
    public javax.swing.JLabel lblcodigo;
    public javax.swing.JLabel lblcondicion;
    public javax.swing.JLabel lblestado;
    public javax.swing.JLabel lblmoneda;
    public javax.swing.JLabel lblnom;
    public javax.swing.JLabel lbltipocliente;
    public javax.swing.JLabel lblvendedor;
    public javax.swing.JTable tbl_bcobrador;
    public javax.swing.JTable tbl_bcondicion;
    public javax.swing.JTable tbl_bmoneda;
    public javax.swing.JTable tbl_bpersona;
    public javax.swing.JTable tbl_btipo_cliente;
    public javax.swing.JTable tbl_bvendedor;
    public javax.swing.JTable tbl_cliente;
    public javax.swing.JTextField txt_bcondicion;
    public javax.swing.JTextField txt_bnombre_cobrador;
    public javax.swing.JTextField txt_bnombre_persona;
    public javax.swing.JTextField txt_bnombre_vendedor;
    public javax.swing.JTextField txt_bnrodoc_persona;
    public javax.swing.JTextField txt_cod_cliente;
    public javax.swing.JTextField txt_cod_cobrador;
    public javax.swing.JTextField txt_cod_condicion;
    public javax.swing.JTextField txt_cod_moneda;
    public javax.swing.JTextField txt_cod_persona;
    public javax.swing.JTextField txt_cod_tipo_cliente;
    public javax.swing.JTextField txt_cod_vendedor;
    public javax.swing.JTextField txt_comentario;
    public javax.swing.JTextField txt_desc_cobrador;
    public javax.swing.JTextField txt_desc_condicion;
    public javax.swing.JTextField txt_desc_moneda;
    public javax.swing.JTextField txt_desc_persona;
    public javax.swing.JTextField txt_desc_tipo_cliente;
    public javax.swing.JTextField txt_desc_vendedor;
    public javax.swing.JTextArea txt_error;
    public javax.swing.JTextField txt_lim_credito;
    public javax.swing.JDialog ventana_cobrador;
    private javax.swing.JDialog ventana_condicion;
    private javax.swing.JDialog ventana_error;
    private javax.swing.JDialog ventana_moneda;
    private javax.swing.JDialog ventana_persona;
    private javax.swing.JDialog ventana_tipo_cliente;
    private javax.swing.JDialog ventana_vendedor;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        bloquea_botones();
        carga_combobox();
        ocultar_label();
    }

    private void bloquea_campos() {
        txt_cod_cliente.setEditable(false);
        txt_cod_cobrador.setEditable(false);
        txt_cod_condicion.setEditable(false);
        txt_cod_moneda.setEditable(false);
        txt_cod_persona.setEditable(false);
        txt_cod_tipo_cliente.setEditable(false);
        txt_cod_vendedor.setEditable(false);
        txt_comentario.setEditable(false);
        txt_desc_cobrador.setEditable(false);
        txt_desc_condicion.setEditable(false);
        txt_desc_moneda.setEditable(false);
        txt_desc_persona.setEditable(false);
        txt_desc_tipo_cliente.setEditable(false);
        txt_desc_vendedor.setEditable(false);
        txt_lim_credito.setEditable(false);
        btn_busq_cod_cob.setEnabled(false);
        btn_busq_cod_cond.setEnabled(false);
        btn_busq_cod_mone.setEnabled(false);
        btn_busq_cod_pers.setEnabled(false);
        btn_busq_cod_tip_cli.setEnabled(false);
        btn_busq_cod_ven.setEnabled(false);
        cmb_estado.setEnabled(false);
    }

    private void bloquea_botones() {
        btn_actualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_ejecutar.setEnabled(false);
        btn_error.setEnabled(false);
        btn_busqueda.setEnabled(true);
        btn_nuevo.setEnabled(true);
        btn_nuevo.requestFocus();
    }

    private void carga_combobox() {
        Object tpd[] = new Object[2];
        tpd[0] ="ACTIVO";
        tpd[1] ="INACTIVO";
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(tpd);
        this.cmb_estado.setModel(dcb);
        //cmb_estado.addItem("Seleccione Opcion");
        String std = "ACTIVO";
        this.cmb_estado.setSelectedItem(std);
    }

    public void habilita_campos() {
        //txt_cod_cliente.setEditable(true);
        txt_cod_cobrador.setEditable(true);
        txt_cod_condicion.setEditable(true);
        txt_cod_moneda.setEditable(true);
        txt_cod_persona.setEditable(true);
        txt_cod_tipo_cliente.setEditable(true);
        txt_cod_vendedor.setEditable(true);
        txt_comentario.setEditable(true);
        txt_desc_cobrador.setEditable(true);
        txt_desc_condicion.setEditable(true);
        txt_desc_moneda.setEditable(true);
        txt_desc_persona.setEditable(true);
        txt_desc_tipo_cliente.setEditable(true);
        txt_desc_vendedor.setEditable(true);
        txt_lim_credito.setEditable(true);
        cmb_estado.setEnabled(true);
        btn_busq_cod_cob.setEnabled(true);
        btn_busq_cod_cond.setEnabled(true);
        btn_busq_cod_mone.setEnabled(true);
        btn_busq_cod_pers.setEnabled(true);
        btn_busq_cod_tip_cli.setEnabled(true);
        btn_busq_cod_ven.setEnabled(true);
        txt_cod_persona.requestFocus();
    }
    public void ventana_persona(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_persona.setVisible(true);
        ventana_persona.setSize(465,415);
        txt_bnrodoc_persona.setText("");
        txt_bnombre_persona.setText("%%");
        ventana_persona.setLocationRelativeTo(bus);
}
    public void ventana_moneda(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_moneda.setVisible(true);
        ventana_moneda.setSize(300,210);
        ventana_moneda.setLocationRelativeTo(bus);
}
    public void ventana_cobrador(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_cobrador.setVisible(true);
        ventana_cobrador.setSize(395,390);
        txt_bnombre_cobrador.setText("%%");
        ventana_cobrador.setLocationRelativeTo(bus);
}
    public void ventana_vendedor(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_vendedor.setVisible(true);
        ventana_vendedor.setSize(395,390);
        txt_bnombre_vendedor.setText("%%");
        ventana_vendedor.setLocationRelativeTo(bus);
}
    public void ventana_condicion_venta(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_condicion.setVisible(true);
        ventana_condicion.setSize(395,390);
        txt_bcondicion.setText("%%");
        ventana_condicion.setLocationRelativeTo(bus);
}
    public void ventana_tipo_cliente(){
        FORMCLIENT bus = new FORMCLIENT();
        ventana_tipo_cliente.setVisible(true);
        ventana_tipo_cliente.setSize(405,380);
        ventana_tipo_cliente.setLocationRelativeTo(bus);
}
    public void cerrar_ventana_persona(){
        ventana_persona.dispose();
}
    public void cerrar_ventana_moneda(){
        ventana_moneda.dispose();
}
    public void cerrar_ventana_cobrador(){
        ventana_cobrador.dispose();
}
    public void cerrar_ventana_vendedor(){
        ventana_vendedor.dispose();
}
    public void cerrar_ventana_condicion_venta(){
        ventana_condicion.dispose();
}
    public void cerrar_ventana_tipo_cliente(){
        ventana_tipo_cliente.dispose();
}
public void ventana_error(){
    FORMCLIENT bus = new FORMCLIENT();
        ventana_error.setVisible(true);
        ventana_error.setSize(590,355);
        ventana_error.setLocationRelativeTo(bus);
}
public void cerrar_ventana_error(){
        ventana_error.dispose();
}
    public void limpia_campos() {
        txt_cod_cliente.setText("");
        txt_cod_cobrador.setText("");
        txt_cod_condicion.setText("");
        txt_cod_moneda.setText("");
        txt_cod_persona.setText("");
        txt_cod_tipo_cliente.setText("");
        txt_cod_vendedor.setText("");
        txt_comentario.setText("");
        txt_desc_cobrador.setText("");
        txt_desc_condicion.setText("");
        txt_desc_moneda.setText("");
        txt_desc_persona.setText("");
        txt_desc_tipo_cliente.setText("");
        txt_desc_vendedor.setText("");
        txt_lim_credito.setText("");
        txt_error.setText("");
        carga_combobox();
    }

    public void ocultar_label() {
        lblcobrador.setVisible(false);
        lblcondicion.setVisible(false);
        lblestado.setVisible(false);
        lblmoneda.setVisible(false);
        lblcod.setVisible(false);
        lbltipocliente.setVisible(false);
        lblvendedor.setVisible(false);
        lblcodigo.setVisible(false);
        lblnom.setVisible(false);
        campo_obligatorio.setVisible(false);
    }
    public void mostrar_campos_requeridos() {
        lblcobrador.setVisible(true);
        lblcondicion.setVisible(true);
        lblestado.setVisible(true);
        lblmoneda.setVisible(true);
        lblnom.setVisible(true);
        lblvendedor.setVisible(true);
        campo_obligatorio.setVisible(true);
        campo_obligatorio.setText("CAMPOS OBLIGATORIOS * ");
        //
        lblcobrador.setForeground(new Color(255,51,51));
        lblcondicion.setForeground(new Color(255,51,51));
        lblestado.setForeground(new Color(255,51,51));
        lblmoneda.setForeground(new Color(255,51,51));
        lblnom.setForeground(new Color(255,51,51));
        lblvendedor.setForeground(new Color(255,51,51));
        campo_obligatorio.setForeground(new Color(255,51,51));
    }
    public void mostrar_campos_busqueda() {
        lblcod.setVisible(true);
        lblnom.setVisible(true);
        campo_obligatorio.setVisible(true);
        campo_obligatorio.setText("CAMPOS DE BUSQUEDA * ");
        //
        lblcodigo.setForeground(new Color(255,51,51));
        lblnom.setForeground(new Color(255,51,51));
        campo_obligatorio.setForeground(new Color(255,51,51));
    }
}
