package vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jony
 */
public class FORMHBCJCO extends javax.swing.JFrame {
    
    /**
     * Creates new form FORMHBCJCO
     */
    public FORMHBCJCO() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializa_controles();
        cerrar_ventan_hab();
    }
private void cerrar_ventan_hab() {
        setDefaultCloseOperation(FORMHBCJCO.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanahab();
            }
        });
    }
   public void cerrar_ventanahab(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_cod_usuario = new javax.swing.JTextField();
        txt_desc_usuario = new javax.swing.JTextField();
        txt_cod_sucursal = new javax.swing.JTextField();
        txt_desc_sucursal = new javax.swing.JTextField();
        txt_nro_habilitacion = new javax.swing.JTextField();
        txt_fecha_hab = new com.toedter.calendar.JDateChooser();
        txt_saldo_inicial = new javax.swing.JTextField();
        cmb_caja = new javax.swing.JComboBox<>();
        btn_habilitar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HABILITACION CAJA(FORMHBCJCO)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)), "HABILITACION CAJA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_cod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));
        jPanel2.add(txt_desc_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 250, -1));
        jPanel2.add(txt_cod_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));
        jPanel2.add(txt_desc_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, -1));
        jPanel2.add(txt_nro_habilitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));
        jPanel2.add(txt_fecha_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 170, -1));
        jPanel2.add(txt_saldo_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, -1));

        cmb_caja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmb_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, -1));

        btn_habilitar.setText("HABILITAR");
        jPanel2.add(btn_habilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Usuario:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Sucursal:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nro Habil:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Fecha Hab:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Monto Inic:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Caja:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMHBCJCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMHBCJCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMHBCJCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMHBCJCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMHBCJCO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_habilitar;
    public javax.swing.JComboBox<String> cmb_caja;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_cod_sucursal;
    public javax.swing.JTextField txt_cod_usuario;
    public javax.swing.JTextField txt_desc_sucursal;
    public javax.swing.JTextField txt_desc_usuario;
    public com.toedter.calendar.JDateChooser txt_fecha_hab;
    public javax.swing.JTextField txt_nro_habilitacion;
    public javax.swing.JTextField txt_saldo_inicial;
    // End of variables declaration//GEN-END:variables

    public void inicializa_controles() {
        bloquea_campos();
        carga_fecha();
    }

    private void bloquea_campos() {
        txt_cod_usuario.setEditable(false);
        txt_desc_usuario.setEditable(false);
        txt_cod_sucursal.setEditable(false);
        txt_desc_sucursal.setEditable(false);
        txt_nro_habilitacion.setEditable(false);
        txt_saldo_inicial.requestFocus();
    }

    private void carga_fecha() {
        try {
            Date hoy = new Date();
            Date fecha = null;
            SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
            String fechaact = formatofecha.format(hoy);
            fecha = formatofecha.parse(fechaact);
            txt_fecha_hab.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(FORMHBCJCO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
