package vista;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jony
 */
public class REPEXTCLI1 extends javax.swing.JFrame {

    /**
     * Creates new form REPCLIFEC1
     */
    public REPEXTCLI1() {
        initComponents();
        this.setLocationRelativeTo(null);
        cerrar_ventan_extr_cl();
    }
public void cerrar_ventan_extr_cl() {
        setDefaultCloseOperation(REPEXTCLI1.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) { 
               cerrar_ventanaextracto();
            }
        });
    }
   public void cerrar_ventanaextracto(){
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere cerrar esta ventana ?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (opc == JOptionPane.YES_OPTION) {
                   this.dispose();
               }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_cliente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_bnomb_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_bcod_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_busq_cliente = new javax.swing.JTable();
        btn_agreg_cliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_ejecutar = new javax.swing.JButton();
        txt_cod_cliente = new javax.swing.JTextField();
        txt_desc_cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_cliente = new javax.swing.JButton();
        cmb_tipo_reporte = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_fecha_hasta = new com.toedter.calendar.JDateChooser();
        txt_fecha_desde = new com.toedter.calendar.JDateChooser();

        ventana_cliente.setTitle("Busqueda Cliente");
        ventana_cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bnomb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bnomb_clienteActionPerformed(evt);
            }
        });
        jPanel4.add(txt_bnomb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Nombre Cliente");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel4.add(txt_bcod_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Ci/Ruc");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        tbl_busq_cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_busq_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_busq_cliente);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 230));

        btn_agreg_cliente.setBackground(new java.awt.Color(255, 102, 0));
        btn_agreg_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agreg_cliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_agreg_cliente.setText("Agregar");
        jPanel4.add(btn_agreg_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 330));

        ventana_cliente.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte de estado de cuenta cliente(REPEXTCLI1)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ejecutar.setBackground(new java.awt.Color(0, 153, 0));
        btn_ejecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ejecutar.setText("EJECUTAR");
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 30));

        txt_cod_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_clienteActionPerformed(evt);
            }
        });
        txt_cod_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(txt_cod_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 25));
        jPanel2.add(txt_desc_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 100, 250, 25));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Cliente:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("PARAMETROS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Fecha Desde:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Tipo Infrome:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btn_cliente.setToolTipText("Buscar");
        jPanel2.add(btn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 100, 25, 25));

        cmb_tipo_reporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RESUMIDO", "DETALLADO", "ANALISIS EN DIAS", "HASTA 30 DIAS", "HASTA 60 DIAS", "HASTA 90 DIAS", "MAS DE 90 DIAS" }));
        jPanel2.add(cmb_tipo_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 200, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Fecha Hasta:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        jPanel2.add(txt_fecha_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 25));
        jPanel2.add(txt_fecha_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void txt_cod_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_clienteActionPerformed

    private void txt_bnomb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bnomb_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bnomb_clienteActionPerformed

    private void txt_cod_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_clienteKeyTyped
       char tecla;
        int num=10;
        tecla=evt.getKeyChar();
        if (!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE) {
           evt.consume();
           getToolkit().beep();
        } 
        if(txt_cod_cliente.getText().length()>=num){
            evt.consume();
        }
    }//GEN-LAST:event_txt_cod_clienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REPEXTCLI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REPEXTCLI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REPEXTCLI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REPEXTCLI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REPEXTCLI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agreg_cliente;
    public javax.swing.JButton btn_cliente;
    public javax.swing.JButton btn_ejecutar;
    public javax.swing.JComboBox<String> cmb_tipo_reporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_busq_cliente;
    public javax.swing.JTextField txt_bcod_cliente;
    public javax.swing.JTextField txt_bnomb_cliente;
    public javax.swing.JTextField txt_cod_cliente;
    public javax.swing.JTextField txt_desc_cliente;
    public com.toedter.calendar.JDateChooser txt_fecha_desde;
    public com.toedter.calendar.JDateChooser txt_fecha_hasta;
    private javax.swing.JDialog ventana_cliente;
    // End of variables declaration//GEN-END:variables
public void ventana_cliente(){
      REPEXTCLI1 bus = new REPEXTCLI1();
        ventana_cliente.setVisible(true);
        ventana_cliente.setSize(405,385);
        ventana_cliente.setLocationRelativeTo(bus);
        txt_bcod_cliente.setText("");
        txt_bnomb_cliente.setText("%%");
    }
public void cerrar_ventana_cliente(){
        ventana_cliente.dispose();
    }
}
